= Protokoll: Beratungsgespräch 2020-01-17
Lukas Grambole <lukas.grambole@htw-dresden.de>
17.01.2020
:toc: 
:toc-title: Inhaltsverzeichnis
:sectnums:
// Platzhalter für weitere Dokumenten-Attribute 



== Organisatorische Angaben
|===
|Datum / Uhrzeit|	Ort|Gesprächsteilnehmer

|17.01.2020 / 15:00 Uhr|HTW Dresden, Z 349b
a| 
* Yewgenij Baburkin (stellvertretender Project Manager, Developer)
* Michael Däbler (Analyst)
* Lukas Grambole (Analyst)
* Christian Grieß (Architect)
* Christian Lehmann (Tester)
* Prof.  Jürgen Anke (Coach)

|===


== Gesprächsinhalte
=== Allgemeine Gesprächsinhalte
* Kundengespräch vom Montag mit vielen inhaltlichen Erweiterungen, technischer Verkleinerung des Scopes und Änderung der Stakeholder
* Coach sieht Verantwortung für Rahmenbedingungen des Projektes nicht beim Projektteam
* Projektteam soll das machen, was die Auftraggeberin fordert
* übergeordnetee Ziele: Prozesse des iterativen Vorgehens lernen, regelmäßiges Arbeiten am Projekt, Iterationstakt einhalten, immer alles aktuell halten
* untergeordnetes Ziel: vollständige Lösung des Kundenproblems, in unserem Fall aber durchaus machbar
* zur Abgabe Vorlage von Herrn Zirkelbach verwenden


=== Analystenbezogene Gesprächsinhalte
* Wiederaufnahme der Stakeholder Studierende und Lehrende
* Beachtung des Risikos falscher Prüfungsbewertungen infolge von falschen Ergebnisausgaben hat nichtfunktionale Anforderung der Korrektheit (unter Reliability) zur Folge
* Use Cases mit Berechnungen eindeutiger formulieren
* Druck- und PDF-Use Cases zusammenfassen
* Anforderungen potenzieller Stakeholder (Lehrende und Studierende) sind zu vernachlässigen



=== Architektenbezogene Gesprächsinhalte
* Charakter des Systems (Desktopapplikation) erwähnen
* Beispiele für Annahmen und Abhängigkeiten: Nutzer verwendet Desktop-PC, Internetverbindung, Bildschirm hat Größe von 22 Zoll, Eingabe mit Maus und Tastatur, Farbdarstellung, keine Nutzer mit Seheinschränkungen, Know-how, Kompetenzniveau der eingebenden Person, ...
* Annahmen und Abhängigkeiten sind "Systemanforderungen rückwärts"
* über nichtfunktionale Anforderungen Architektur erarbeiten
* weitere Anregungen: installationsfrei, Größe
* Wo schreibe ich bei Start von USB-Stick die Daten hin?
* Ziel der Architektur ist nicht, das alles optimal sein soll. Die richtige Herangehensweise lautet: Ich entscheide mich für etwas, weil ich es gut kann und es geeignet ist.
* Unser Entwurf für die Architektur ist grundsätzlich gut.
* Verbesserungsanreize: eventuelle Alternativen (Java) und Abwahlgründe eingeben, Adressierung der nichfunktionalen Anforderung der Korrektheit, Wie visualisiere ich Sachen?
* Notizbuchcharakter
* Was uns nicht betrifft ist wegzulassen? (z.B. Schlüssel/Abstraktion)
* Wenn das Architecture Notebook länger als 6 A4 Seiten ist, dann ist es wahrscheinlich falsch.
* keine Erklärugen (z.B. zum Thema: Was ist Python?)
* Architektonische Mechanismen: Persistenz, Berechtigungsprüfung, grafische Benutzeroberfläche, ...

