= Architecture Notebook Bauphysik
Christian Grieß <christian.Griess@htw-dresden.de>;
0.8, 18.01.2020
:toc: 
:toc-title: Inhaltsverzeichnis
:sectnums:
// Platzhalter für weitere Dokumenten-Attribute 


== Zweck



Dieses Dokument beschreibt die Philosophie, Entscheidungen, Nebenbedingungen, Begründungen, wesentliche Elemente und andere übergreifende Aspekte des Systems, die Einfluss auf Entwurf und Implementierung haben.

//Hinweise: Bearbeiten Sie immer die Abschnitte 2-6 dieser Vorlage. Nachfolgende Abschnitte sind empfohlen, aber optional und sollten je nach Umfang der künftigen Wartungsarbeiten, Fähigkeiten des Entwicklungsteams und Bedeutung anderer architektureller Belange. 

//Anmerkung: Die Architektur legt wesentliche EINSCHRÄNKUNGEN für den Systementwurf fest und ist ein Schlüssel für die Erfüllung nicht-funktionaler Eigenschaften!



== Architekturziele und Philosophie

Folgende Architektur bezieht sich auf eine Softwarelösung die ohne Installation über ein USB-Speichermedium auszuführen sein soll. +
Die Auftraggebende Person wünscht sich ein, vom Internet, unabhängiges Programm. +
Sie möchte ein Wartungsfreies Produkt. +
Außerdem wird nicht erwartet, dass sich in Zukunft etwas an der Systemumgebung ändern wird. +
Es ist nur für die Eigenbenutzung gedacht (kurzfristige Nutzung durch andere möglich). +
Die Software ist für Speziallisten in dem Gebiet der Bauphysik und soll für diese einfach zu bedienen sein. +

== Annahmen und Abhängigkeiten
. Nutzer verwenden Dekstop-PC oder Laptop mit USB-Port.
. Endgeräte laufen unter Windows 10.
. Eingabegeräte sind Maus(Touchpad) und Tastatur.
. Keine Maßnahmen zur Barrierefreiheit nötig.
. Nutzung ausschließlich durch Speziallisten der Bauphysik.
. Keine Internetanbindung vorhanden.

//[List the assumptions and dependencies that drive architectural decisions. This could include sensitive or critical areas, dependencies on legacy interfaces, the skill and experience of the team, the availability of important resources, and so forth]

== Architektur-relevante Anforderungen
 Architecturally significant requirements are those requirements that play an important role in determining the architecture of the system.  Such requirements require special attention. Not all requirements have equal significance with regards to the architecture.

Architecturally significant requirements are a subset of the requirements that need to be satisfied before the architecture can be considered "stable". Typically, these are requirements that are technically challenging, technically constraining, or central to the system's purpose. Furthermore, the system will generally be more sensitive to changes against architecturally significant requirements, so identifying and communicating this subset will help others understand the potential implications of change.

Requirements can be explicitly or implicitly architecturally significant. Explicitly significant requirements are often overtly technical in nature, such as performance targets; the need to interface to other systems; the number of users that must be supported; or security requirements. Implicitly significant requirements may define the essence of the functional behaviour of the system (for example, making a purchase from an on-line store).

Deciding whether a specific requirement is architecturally significant is often a matter of judgment. The selection of requirements that are considered "architecturally significant" is driven by several key driving factors:

    The benefit of the requirement to stakeholders: critical, important, or useful.
    The architectural impact of the requirement: none, extends, or modifies. There may be critical requirements that have little or no impact on the architecture and low-benefit requirements that have a big impact. Low-benefit requirements with big architectural impacts should be reviewed by the project manager for possible removal from the scope of the project.
    The risks to be mitigated: performance, availability of a product, and suitability of a component.
    The completion of the coverage of the architecture.
    Other tactical objectives or constraints, such as demonstration to the user, and so on.

There may be two requirements that hit the same components and address similar risks. If you implement A first, then B is not architecturally significant. If you implement B first, then A is not architecturally significant. Thus these attributes can depend on the order the requirements are realized, and should be re-evaluated when the order changes, as well as when the requirements themselves change.

The following are good examples of Architecturally Significant Requirements:

    The system must record every modification to customer records for audit purposes.
    The system must respond within 5 seconds.
    The system must deploy on Microsoft Windows XP and Linux.
    The system must encrypt all network traffic.
    The ATM system must dispense cash on demand to validated account holders with sufficient cleared funds.

Architecturally significant requirements also describe key behaviors that the system needs to perform.  Such scenarios represent the important interactions between key abstractions.and should be identified as architecturally significant requirements. For example, for an on-line book store describing the way the software handles the scenarios for ordering a book and checking out the shopping cart are often enough to communicate the essence of the architecture. 


Es gibt keine wichtigen Vorraussetzungen.
//Fügen Sie eine Referenz / Link zu den Anforderungen ein, die implementiert werden müssen, um die Architektur zu erzeugen.


== Entscheidungen, Nebenbedingungen und Begründungen

//[List the decisions that have been made regarding architectural approaches and the constraints being placed on the way that the developers build the system. These will serve as guidelines for defining architecturally significant parts of the system. Justify each decision or constraint so that developers understand the importance of building the system according to the context created by those decisions and constraints. This may include a list of DOs and DON’Ts to guide the developers in building the system.] 

. Software wird mit dem GUI tool PyQT in Python geschrieben (GNU / GPL License). 
// Für unsere Developer PyQT: https://www.qt.io/blog/2018/12/18/qt-python-5-12-released GNU / GPL License) +
.. Obwohl unsere Developer keine Erfahrung mit Python/QT haben, wollen wir dieses Projekt nutzen um uns Grundkenntnisse anzueignen.

//ANALYSTEN TEXT

// Contribution via Open Source

//When selecting an open source license for your project, you contribute to free and open source software development by using //Qt under any of the following licenses: LGPL version 3, GPL version 2 and GPL version 3.

//Basic Premises of the Qt Open Source Model

//GPL – All users have the rights to obtain, modify and redistribute the full source code of your application. Your users are //granted rights founded on the four freedoms of the GNU General Public License.

//LGPL – Any modification to a Qt component covered by the GNU Lesser General Public License must be contributed back to the //community. This is the primary open source Qt license, which covers the majority of Qt modules.

//Please note that there are parts of Qt that are only provided under GPL for open source users that will require you to license //your application under a GPL compatible license. Qt also ships with third party open source components that might require //respective licensing compliancy, if used. See details of other licenses inside Qt .

//icon_resources_infographicCheck out which components are available under the different open source models in the Qt Product //Map.
//Open Source Usage Obligations  

//The majority of the Qt modules are available under the LGPL v3 and GPL v3 open source license. When developing under this //license your obligations are to:

//Provide a re-linking mechanism for Qt libraries
//Provide a license copy & explicitly acknowledge Qt use
//Make a Qt source code copy available for customers
//Accept that Qt source code modifications are non-proprietary
//Make “open” consumer devices
//Accept Digital Rights Management terms, please see the GPL FAQ
//Take special consideration when attempting to enforce software patents FAQ

== Architekturmechanismen
Persistenz ? +
https://de.wikipedia.org/wiki/Persistenz_(Informatik) +




Lokalisation +
Die Software wird nur in deutsch gehalten, auf jeden fall bezüglich der ersten Verion. +
Aber, jede der Individuellen Komponenten sollte technisch auch die Englische Sprache unterstützen. +
https://www2.htw-dresden.de/~anke/openup/core.tech.common.extend_supp/guidances/concepts/arch_mechanism_2932DFB6.html[Doku "Concept: Architectural Mechanism"]
//[List the architectural mechanisms and describe the current state of each one. Initially, each mechanism may be only name and a brief description. They will evolve until the mechanism is a collaboration or pattern that can be directly applied to some aspect of the design.]

//Beispiele: relationales DBMS, Messaging-Dienste, Transaktionsserver, Webserver, Publish-Subscribe Mechanismus

//Beschreiben Sie den Zweck, Eigenschaften und Funktion der Architekturmechanismen.

. Architekturmechanismus 1

. Architekturmechanismus 2


== Schlüssel Abstraktionen 
//[List and briefly describe the key abstractions of the system. This should be a relatively short list of the critical concepts that define the system. The key abstractions will usually translate to the initial analysis classes and important patterns.]

== Schichten oder Architektonisches Framework
//[Describe the architectural pattern that you will use or how the architecture will be consistent and uniform. This could be a simple reference to an existing or well-known architectural pattern, such as the Layer framework, a reference to a high-level model of the framework, or a description of how the major system components should be put together.]

== Architektursichten (Views) 
//[Describe the architectural views that you will use to describe the software architecture. This illustrates the different perspectives that you will make available to review and to document architectural decisions.]

Folgende Sichten werden empfohlen:

=== Logische Sicht
//Beschreibt die Struktur und das Verhalten Systemteilen, die hohen Einfluss auf die Architektur haben. Dies kann die Paketstruktur, kritische Schnittstellen, wichtige Klassen und Subsysteme sowie die Beziehungen zwischen diesen Elementen enthalten. Zudem sollten die physische und logische Sicht persistenter Daten beschrieben werden, wenn es diesen Aspekt im System gibt. Dies ist ein hier dokumentierter Teilaspekt des Entwurfs.


=== Physische Sicht (Betriebssicht)
//Beschreibt die physischen Knoten (Rechner) des Systems, der Prozesse, Threads und Komponenten, die in diesen Knoten ausgeführt werden. Diese Sicht wird nicht benötigt, wenn das System in einem einzelnen Prozess oder Thread ausgeführt wird.

=== Use cases
include::https://github.com/fowado/BauphysikSE1/blob/master/UseCase/usecase_model.adoc[Use Cases]
