= Betriebsdokumentation
:toc: 
:toc-title: Inhaltsverzeichnis
:sectnums:

== Systemvorraussetzungen

* *Mindestanforderungen*
** handelsüblicher Rechner + Komponenten ( Maus, Tastatur)
** Prozessor mit 1 GHz (oder schneller) oder ein SoC-System 
** RAM: 1 GB für 32 Bit oder 2 GB für 64 Bit 
** Festplattenspeicher: 16 GB für 32-Bit-Betriebssystem oder 32 GB für 64-Bit-Betriebssystem 
** Grafikkarte: DirectX 9 oder höher mit WDDM 1.0 Treiber 
** Display: 800 x 600

* *Softwareanforderungen*
** Windows 10
** Mindestens Python 3.8

== Systemeinrichtung
*Komponente*
* .exe /
* .dll / 
* .dist /
* .pyc /
* .py

* *Installation* 
 ** Es ist keine Installation notwendig, die Kundin führt eine Executable (.exe) aus. Das Executable wird der Kundin als Download über den HTW-Cloudspeicherplatz (Owncloud) zur Verfügung gestellt. Dafür wird auf dem Cloudspeicherplatz des Teammanagers (Denis Klassowski) ein neuer Ordner angelegt, in dem das aktuelle Release der Software liegt.

* *Sonstige Bestandteile*
** Kein Passwortschutz 
   (eventuell für den Download-Ordner )
** Ein  Internetzugang wird nur für den Download benötigt, für die Nutzung ist keine   
   Netzanbindung notwendig.

== Systembetreuung 

* *FAQ* 
** Sie haben Fragen an das Programm? -> Sie können sich an Denis Klassowski (denis.klassowski@htw-dresden.de) wenden.
** Was soll ich tun, wenn das Programm nicht oder fehlerhaft startet?
-> Datein erneut und vollständig herunterladen & überprüfen ob alle notwendigen Files im Verzeichnis liegen.
** Wo sind meine Datein gespeichert? -> Alle gespeicherten Datein werden als .baup in das gewünschte Verzeichnis gespeichert. Zum Aufruf der Datei, öffnen Sie das Programm und öffnen Sie Ihre .baup Datei.
** Was soll ich tun, wenn meine .baup nicht lädt -> Wohlmöglich, ist Ihre Datei fehlerhaft, Sie können Ihre Datei als .txt öffnen und manuell Änderungen vornehmen.

* *Datensicherung und Datenwiederherstellung*
** Sie können Ihre Berechnungen speichern und  zu einen späteren Zeitpunkt wieder aufrufen
** Bei einem Programmabsturz, werden sämtliche nicht gespeicherte Eingangsdaten gelöscht 



















