= Work Product (Artifact): Test Case

This artifact is the specification of a set of test inputs, execution conditions, and expected results that you identify to evaluate a particular aspect of a scenario.

== Purpose

    . to provide a way to capture test inputs, conditions, and expected results for a system
    . to systematically identify aspects of the software to test
    . to specify whether an expected result has been reached, based on the verification of a system requirement, set of requirements, or scenario

== Main Description

A test case specifies the conditions that must be validated to enable an assessment of aspects of the system under test. A test case is more formal than a test idea; typically, a test case takes the form of a specification. In less formal environments, you can create test cases by identifying a unique ID, name, associated test data, and expected results.

Test cases can be derived from many sources, and typically include a subset of the requirements (such as use cases, performance characteristics, and reliability concerns) and other types of quality attributes.

== Impact of not Having

Without this artifact, it is difficult to validate system functionality. Because this artifact specifies the conditions of acceptance between the stakeholders and the developers, without the artifact, it is difficult to establish exit criteria and to demonstrate that the exit criteria have been met. If the original test cases have not been documented, it is impossible to do regression testing. 

== Template

include::TestCase_spec.adoc[]