# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'master.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("BauphysikSE2")
        MainWindow.resize(1076, 842)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1061, 781))
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.ButtonSave = QtWidgets.QPushButton(self.tab)
        self.ButtonSave.setGeometry(QtCore.QRect(860, 20, 75, 23))
        self.ButtonSave.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.ButtonSave.setObjectName("ButtonSave")
        self.ButtonLoad = QtWidgets.QPushButton(self.tab)
        self.ButtonLoad.setGeometry(QtCore.QRect(950, 20, 75, 23))
        self.ButtonLoad.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.ButtonLoad.setObjectName("ButtonLoad")
        self.frameTabContent = QtWidgets.QFrame(self.tab)
        self.frameTabContent.setGeometry(QtCore.QRect(0, 50, 1051, 731))
        self.frameTabContent.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.frameTabContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTabContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTabContent.setObjectName("frameTabContent")
        self.ScrollCircumstances = QtWidgets.QScrollArea(self.frameTabContent)
        self.ScrollCircumstances.setGeometry(QtCore.QRect(10, 10, 441, 311))
        self.ScrollCircumstances.setWidgetResizable(True)
        self.ScrollCircumstances.setObjectName("ScrollCircumstances")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 439, 309))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.FrameTemp = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.FrameTemp.setGeometry(QtCore.QRect(0, 0, 441, 91))
        self.FrameTemp.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.FrameTemp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameTemp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameTemp.setObjectName("FrameTemp")
        self.label = QtWidgets.QLabel(self.FrameTemp)
        self.label.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.FrameTemp)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 47, 13))
        self.label_2.setObjectName("label_2")
        self.doubleSpinBoxTempOut = QtWidgets.QDoubleSpinBox(self.FrameTemp)
        self.doubleSpinBoxTempOut.setGeometry(QtCore.QRect(180, 10, 62, 22))
        self.doubleSpinBoxTempOut.setToolTipDuration(3)
        self.doubleSpinBoxTempOut.setObjectName("doubleSpinBoxTempOut")
        self.label_3 = QtWidgets.QLabel(self.FrameTemp)
        self.label_3.setGeometry(QtCore.QRect(280, 10, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.FrameTemp)
        self.label_4.setGeometry(QtCore.QRect(90, 50, 47, 13))
        self.label_4.setObjectName("label_4")
        self.doubleSpinBoxTempIn = QtWidgets.QDoubleSpinBox(self.FrameTemp)
        self.doubleSpinBoxTempIn.setGeometry(QtCore.QRect(180, 50, 62, 22))
        self.doubleSpinBoxTempIn.setToolTipDuration(3)
        self.doubleSpinBoxTempIn.setObjectName("doubleSpinBoxTempIn")
        self.label_5 = QtWidgets.QLabel(self.FrameTemp)
        self.label_5.setGeometry(QtCore.QRect(280, 50, 47, 13))
        self.label_5.setObjectName("label_5")
        self.ScrollCircumstances.setWidget(self.scrollAreaWidgetContents)
        self.graphicsView = QtWidgets.QGraphicsView(self.frameTabContent)
        self.graphicsView.setGeometry(QtCore.QRect(460, 10, 581, 311))
        self.graphicsView.setObjectName("graphicsView")
        self.scrollArea = QtWidgets.QScrollArea(self.frameTabContent)
        self.scrollArea.setGeometry(QtCore.QRect(10, 370, 1041, 341))
        self.scrollArea.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1039, 339))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.FrameLayer2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.FrameLayer2.setGeometry(QtCore.QRect(0, 70, 1031, 71))
        self.FrameLayer2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameLayer2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameLayer2.setObjectName("FrameLayer2")
        self.label_8 = QtWidgets.QLabel(self.FrameLayer2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_8.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.FrameLayer2)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 47, 13))
        self.label_9.setObjectName("label_9")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.FrameLayer2)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(70, 40, 62, 22))
        self.doubleSpinBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.FrameLayer2)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 40, 69, 22))
        self.comboBox_2.setToolTipDuration(3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.FrameLayer2)
        self.pushButton_2.setGeometry(QtCore.QRect(950, 0, 75, 23))
        self.pushButton_2.setToolTipDuration(3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.FrameAddLayer = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.FrameAddLayer.setGeometry(QtCore.QRect(0, 140, 1031, 31))
        self.FrameAddLayer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameAddLayer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameAddLayer.setObjectName("FrameAddLayer")
        self.label_10 = QtWidgets.QLabel(self.FrameAddLayer)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_10.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.label_10.setObjectName("label_10")
        self.pushButton_3 = QtWidgets.QPushButton(self.FrameAddLayer)
        self.pushButton_3.setGeometry(QtCore.QRect(950, 0, 75, 23))
        self.pushButton_3.setToolTipDuration(3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.FrameLayer1 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.FrameLayer1.setGeometry(QtCore.QRect(0, 0, 1031, 71))
        self.FrameLayer1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameLayer1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameLayer1.setObjectName("FrameLayer1")
        self.label_6 = QtWidgets.QLabel(self.FrameLayer1)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_6.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.FrameLayer1)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 47, 13))
        self.label_7.setObjectName("label_7")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.FrameLayer1)
        self.doubleSpinBox.setGeometry(QtCore.QRect(70, 40, 62, 22))
        self.doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.comboBox = QtWidgets.QComboBox(self.FrameLayer1)
        self.comboBox.setGeometry(QtCore.QRect(150, 40, 69, 22))
        self.comboBox.setToolTipDuration(3)
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(self.FrameLayer1)
        self.pushButton.setGeometry(QtCore.QRect(950, 0, 75, 23))
        self.pushButton.setToolTipDuration(3)
        self.pushButton.setObjectName("pushButton")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.ButtonGraph = QtWidgets.QPushButton(self.frameTabContent)
        self.ButtonGraph.setGeometry(QtCore.QRect(10, 340, 75, 23))
        self.ButtonGraph.setToolTip("")
        self.ButtonGraph.setToolTipDuration(3)
        self.ButtonGraph.setWhatsThis("")
        self.ButtonGraph.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.ButtonGraph.setObjectName("ButtonGraph")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 21))
        self.menubar.setObjectName("menubar")
        self.menuLanguage = QtWidgets.QMenu(self.menubar)
        self.menuLanguage.setObjectName("menuLanguage")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDeutsch = QtWidgets.QAction(MainWindow)
        self.actionDeutsch.setObjectName("actionDeutsch")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.menuLanguage.addAction(self.actionDeutsch)
        self.menuLanguage.addAction(self.actionEnglish)
        self.menubar.addAction(self.menuLanguage.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ButtonSave.setText(_translate("MainWindow", "Speichern"))
        self.ButtonLoad.setText(_translate("MainWindow", "Laden"))
        self.FrameTemp.setToolTip(_translate("MainWindow", "Temperatur in °C"))
        self.label.setText(_translate("MainWindow", "Temp"))
        self.label_2.setText(_translate("MainWindow", "außen"))
        self.doubleSpinBoxTempOut.setToolTip(_translate("MainWindow", "Temperatur in °C"))
        self.label_3.setText(_translate("MainWindow", "°C"))
        self.label_4.setText(_translate("MainWindow", "innen"))
        self.doubleSpinBoxTempIn.setToolTip(_translate("MainWindow", "Temperatur in °C"))
        self.label_5.setText(_translate("MainWindow", "°C"))
        self.label_8.setText(_translate("MainWindow", "Schicht 2"))
        self.label_9.setText(_translate("MainWindow", "Dicke"))
        self.comboBox_2.setToolTip(_translate("MainWindow", "Einheit auswählen"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "Schicht entfernen"))
        self.pushButton_2.setText(_translate("MainWindow", "löschen"))
        self.label_10.setText(_translate("MainWindow", "Schicht 3"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "Schicht hinzufügen"))
        self.pushButton_3.setText(_translate("MainWindow", "hinzufügen"))
        self.label_6.setText(_translate("MainWindow", "Schicht 1"))
        self.label_7.setText(_translate("MainWindow", "Dicke"))
        self.comboBox.setToolTip(_translate("MainWindow", "Einheit auswählen"))
        self.pushButton.setToolTip(_translate("MainWindow", "Schicht entfernen"))
        self.pushButton.setText(_translate("MainWindow", "löschen"))
        self.ButtonGraph.setStatusTip(_translate("MainWindow", "Zeigt einen Graphen an"))
        self.ButtonGraph.setText(_translate("MainWindow", "Visualisieren"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuLanguage.setTitle(_translate("MainWindow", "Language"))
        self.actionDeutsch.setText(_translate("MainWindow", "Deutsch"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
