//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).
== Use Case: Materialdaten ändern

=== Kurzbeschreibung
//<Kurze Beschreibung des Use Case>

Der Use Case beschreibt einen Vorgang zur Änderung, Löschung, oder Erstellung von Materialdaten.

=== Kurzbeschreibung der Akteure
*Systemnutzer*

will Materialdaten hinzufügen, verändern, oder löschen.


=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...
* Der Systemnutzer hat das Softwaresystem gestartet.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Systemnutzer die Funktion zur Änderung von Materialdaten öffnet.
. Das Softwaresystem erstellt eine Übersicht mit allen gespeicherten Materialdaten.
. _IF_ Systemnutzer möchte ein Material hinzufügen
.. Der Systemnutzer öffnet die Funktion zum Hinzufügen eines Materials
.. Der Systemnutzer gibt Materialdaten ein
.. _INCLUDE_ Plausibilität prüfen
.. Der Systemnutzer bestätigt seine Angabe
.. Das Softwaresystem speichert die Eingaben
. _IF_ Systemnutzer möchte ein Material löschen
.. Der Systemnutzer wählt ein Material aus der Übersicht aus
.. Der Systemnutzer wählt die Löschfunktion
.. Das Softwaresystem bittet um Bestätigung der Löschung
.. Der Systemnutzer bestätigt die Löschung
.. Das Softwaresystem löscht die Daten des ausgewählten Materials
. _IF_ Systemnutzer möchte vorhandene Materialdaten ändern
.. Der Systemnutzer wählt ein Material aus der Übersicht aus
.. Der Systemnutzer wählt die Änderungsfunktion
.. Das Softwaresystem ermöglicht die Änderung der Materialdaten
.. Der Systemnutzer gibt Materialdaten ein.
.. _INCLUDE_ Plausibilität prüfen
.. Der Systemnutzer bestätigt seine Eingaben
.. Das Softwaresystem speichert die Materialdaten
. Der Systemnutzer schließt die Funktion zur Änderung der Materialdaten
. Der Use Case ist abgeschlossen.


=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.
* *SC1:* Der Systemnutzer wählt die Funktion zur Editierung von Materialdaten aus, erstellt ein neues Material und gibt dessen Daten ein. Anschließend beendet er die Funktion zur Editierung von Materialdaten. Die Daten wurden erfolgreich editiert.

* *SC2:* Der Systemnutzer wählt die Funktion zur Editierung von Materialdaten aus, wählt ein Material aus und löscht dessen Materialdaten. Anschließend beendet er die Funktion zur Editierung von Materialdaten. Die Daten wurden erfolgreich editiert.

* *SC3:* Der Systemnutzer wählt die Funktion zur Editierung von Materialdaten aus, wählt ein Material aus und ändert dessen Materialdaten. Anschließend beendet er die Funktion zur Editierung von Materialdaten. Die Daten wurden erfolgreich editiert.

* *SC4:* Der Systemnutzer wählt die Funktion zur Editierung von Materialdaten aus und schaut sich die gespeicherten Materialdaten an. Anschließend beendet er die Funktion zur Editierung von Materialdaten. Die Daten wurden nicht editiert. Der Use Case wurde erfolgreich abgeschlossen.



=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.
* Es bestehen keine Nachbedingungen, da bei SC4 der Use Case trotz Ergebnislosigkeit erfolgreich beendet werden kann.
