= Reflexion SE2 Yewgenij Baburkin

Im Rahmen des Projektes hatte ich die Position eines Entwicklers. Obwohl wir nicht tatsächlich ein Model-View-Presenter-Modell verwendet haben, kann man sich meine Tätigkeit ungefähr insofern vorstellen, dass ich für View und Presenter zuständig war.
Die Organisation des Projektes war am Anfang etwas chaotisch, da für viele - wenn nicht gar alle - von uns dieses Projekt die erste praktische und tatsächliche Umsetzung von OpenUP war. Nachdem man aber diese Anfangshürde überwunden hatte, ging es strukturierter voran. Dies führte natürlicch zu einem Lerneffekt bezüglich agiler Entwicklung und zwischenmenschlicher Kommunikation und Organisation.
Für mich persönlich gab es den größten Lerneffekt im Zusammenhang mit der gewählten Programmiersprache und des gewählten Frameworks. Da ich zuvor nie wirklich in Python programmiert hatte und zudem noch nie mit QT in Berührung gekommen bin, sah ich darin die größte Hürde. Trotz unzureichender Dokumentation für QT in Python und Schwierigkeiten bei Fragestellungen auch Antworten für QT5, welches wesentliche Unterschiede zu QT4 aufweist, zu finden, kann ich nun sagen, dass ich in Python auch in Verbindung mit QT ein Projekt programmieren kann bzw. könnte. Besonders positiv ist hierbei unser Projektmanager Denis zu erwähnen, da er arbeitstechnisch auch mit QT in Berührung kam und mir somit bei Fragestellungen schnell und konstruktiv zur Hilfe kommen konnte.
Stolz bin ich vor allem darauf, dass meine Grundidee für die UI positiv aufgenommen wurde und im Endprodukt auch mit minimalen Abänderungen implementiert erfolgreich implementiert 