= Reflexion SE2 Yewgenij Baburkin

Im Rahmen des Projektes hatte ich die Position eines Entwicklers. Obwohl wir nicht tatsächlich ein Model-View-Presenter-Modell verwendet haben, kann man sich meine Tätigkeit ungefähr insofern vorstellen, dass ich für View und Presenter zuständig war.
Die Organisation des Projektes war am Anfang etwas chaotisch, da für viele - wenn nicht gar alle - von uns dieses Projekt die erste praktische und tatsächliche Umsetzung von OpenUP war. Nachdem man aber diese Anfangshürde überwunden hatte, ging es strukturierter voran. Dies führte natürlich zu einem Lerneffekt bezüglich agiler Entwicklung und zwischenmenschlicher Kommunikation und Organisation.
Für mich persönlich gab es den größten Lerneffekt im Zusammenhang mit der gewählten Programmiersprache und des gewählten Frameworks. Da ich zuvor nie wirklich in Python programmiert hatte und zudem noch nie mit QT in Berührung gekommen bin, sah ich darin die größte Hürde. Trotz unzureichender Dokumentation für QT in Python und Schwierigkeiten bei Fragestellungen auch Antworten für QT5 zu finden, welches wesentliche Unterschiede zu QT4 aufweist, kann ich nun sagen, dass ich in Python auch in Verbindung mit QT ein Projekt programmieren kann bzw. könnte. Besonders positiv ist hierbei unser Projektmanager Denis zu erwähnen, da er arbeitstechnisch auch mit QT in Berührung kam und mir somit bei Fragestellungen schnell und konstruktiv zur Hilfe kommen konnte. Getestet wurde unter anderem auch meine Flexibiltät, da ich auch öfter mal im Model-Teil arbeiten musste. Leider hatte unser anderer Entwickler eine Neigung dazu in (für uns) unerklärliche Funkstille zu versinken. 
Stolz bin ich vor allem darauf, dass meine Grundidee für die UI positiv aufgenommen wurde und ich im Endprodukt mit minimalen Abänderungen implementiert erfolgreich implementiert habe. Hierbei habe ich jedoch gemerkt, dass ich gerne meine Fähigkeiten im Bereich UI-Design strukturiert ausbauen würde z.B. mit einem entsprechenden Modul. Darüber hinaus können wir als Team natürlich stolz darauf sein der Kundin das Produkt geliefert zu haben, welches sie auch wollte. Schon in der "Beta-Phase", in welcher die teilweise unfertige Software zu Feedbackzwecken der Kundin übergeben wurde, lies sie vermerken, dass bereits zu dem Zeitpunkt das Programm ihr einen Mehrwert geschaffen hatte.
Positiv in Erinnerung verbleiben kleinere Dev-Meetings, die meist aus einer Variation aus Projektmanager, Architekt, Tester, dem anderen Dev (sofern dieser zu erreichen war) und mir bestanden. In diesen ließen sich genauere Probleme der Umsetzung bereden und manchmal auch direkt lösen. In diesen kam es im Endeffekt auch öfter zu Pair Programming Sessions, welche am Anfang gewöhnungsbedürftig erschienen, jedoch dank Bildschirmübertragung relativ schnell zum Erfolg führten.
Beim nächsten Projekt würde ich dem Architekten eindeutig Feedback geben, dass zumindest meiner Meinung nach Python und UI-Entwicklung vielleicht nicht die beste Kombination ist und man (vor allem, wenn man schon vorgegeben hat, dass es eine Windows-Anwedung sein soll) andere Tools in Betracht ziehen sollte. Zudem würde ich einen stärkeren Fokus auf Kommunikation zwischen den einzelnen Devs setzen, sodass vor allem die Construction Phase angenehmer zu absolvieren ist. Darüber hinaus habe ich bemerkt, dass meine Zeitvorstellungen (Aufwand) trotz eingeplanter Reserve zu optimistisch sind, sofern ich mich in neuen Umgebungen erst zurecht finden muss. 