= Reflexion SE II Felix Fritzsche

Das Softwareprojekt in SE II hat unser Team aufgrund der besonderen Umstände (Kontaktbeschränkungen und Online-Lehre) vor einige Herausforderungen gestellt. Es galt, die Zusammenarbeit einer größeren Gruppe zu organisieren und durchzuführen. Gerade da dieses Projekt auch größer ist als bisherige Belegarbeiten. In unserem Team hatte sich nach kurzen Startschwierigkeiten relativ schnell eine Vorgehensweise etabliert, wie wir mit dieser Situation umgehen wollen. Diese bestand zum einen aus einer WhatsApp-Gruppe für teaminterne Absprachen und die Terminfindung für Meetings. Die Meetings wurden dann per Discord abgehalten, wobei sich vor allem die Möglichkeit seinen Bildschirm für andere freizugeben als besonders nützlich erwiesen hat. Die einzelnen Iterationen wurden per Videokonferenz geplant und mittels GitHub umgesetzt. Dabei wurde die Aufgabenplanung- und verteilung über GitHub Issues realisiert.

Aufgefallen ist während des Projektes auf jeden Fall, dass kontinuierliche Organisation und Kommunikation der Schlüssel zum Erfolg sind. Dabei hat sich vor allem die zeitintensive, weil asynchrone, Kommunikation im Team und auch zur Kundin bemerkbar gemacht. Begegnet sind wir diesem Umstand mit vielen Meetings, auch in kleineren Gruppen.

Gelernt habe ich dabei das schnelle Anpassen an neue Situationen und die Arbeit mit neuen Technologien und Werkzeugen. Gerade der Umgang mit Git und GitHub Issues zur Projektorganisation wird sich im Berufsleben als nützlich erweisen. Die Praktika von Herrn Zirkelbach waren eine hervorragende Grundlage dafür. Auch konnte bereits erlangtes Wissen aus den ersten drei Semestern gut eingesetzt werden.

Ich bin stolz, dass unser Team trotz der besonderen Situation eine funktionierende Software entwickelt hat, welche die Anforderungen unserer Kundin erfüllt und einen Mehrwert für sie bietet. Das positive Feedback der Kundin, schon zur ersten Beta-Version, hat uns darin bestärkt, ein erfolgreiches Projekt absolviert zu haben.

Ich würde bei nächsten Projekten gerne, soweit es die Umstände wieder zulassen, die Scrum-Vorgehensweise ausprobieren. Ich sehe hier den Vorteil einer gesteigerten Effektivität durch die Selbstorganisation des Teams. Die Auswirkungen der Verschiebung von Komplexität weg von der Dokumentation hin zur Kommunikation innerhalb des Teams würde ich gerne erproben.

Zusammenfassend lässt sich sagen, dass das Modul Software Engineering die erlernten Fähigkeiten in einen größeren Kontext einordnet und man viele praxisnahe Erfahrungen sammeln konnte.
