= Reflexion SE2 Christian Lehmann

Während der Durchführung des Projektes Bauphysik habe ich die Funktion als Tester übernommen. Den größten Teil der verrichteten Arbeit nahm die Erstellung der Testfälle und der zugehörigen Testabläufe ein. Die Testfälle leitete ich dabei von den Anforderungen und UseCases ab. Der weitere wesentliche Abschnitt meiner Tätigkeit im Projekt war natürlich das Testen der verschiedenen Funktionen. Kurz gesagt die Durchführung der Testabläufe und die strukturierte Dokumentation der Ergebnisse. +
In jedem Fall habe ich während des gesamten Beleges gelernt, wie man größere Projekte organisieren soll, beziehungsweise sollte. Natürlich hat nicht alles auf Anhieb so geklappt, wie es theoretisch am besten geht. Die grundlegenden Abläufe agiler Entwicklung konnte ich trotzdem gut verinnerlichen und anwenden. Einen großen Lerneffekt gab es für mich bei der strukturierten Dokumentation der Testfälle, aber vor allem der Testergebnisse im TestLog. Generell ist die Organisation und der Inhalt der Workproducts deutlich klarer geworden. Einen sehr großen Lerneffekt bezüglich automatisierten Tests stellten dabei die zum Thema Unittest angebotenen Praktika dar. Anhand dieser Übung erstellte ich die automatisierten Tests. Für mich in der Funktion als Tester ergab sich ein umfassender Überblick über das gesamte Projekt. Angefangen von der Anforderungsanalyse, von der die UseCases abgeleitet wurden und davon dann die von mir verfassten TestCases. Eine wichtige Erkenntnis war, dass man bei der Erstellung und Ausführung von Testabläufen sehr genau sein muss, da Fehler an dieser Stelle einfach zur Vermutung von fehlerhafter Software führen können. Es müsste quasi einen Test für Tests geben. Weiterhin stellt es sich als sehr wichtig dar, genau und lückenlos miteinander zu kommunizieren, damit keine Missverständnisse auftreten und es zu jedem Aspekt im Projekt eine abgestimmte Vorstellung innerhalb des Teams gibt. Dies kann deutlich Zeit sparen beispielsweise bei der Erstellung eines Tests, wenn Tester und Developer die gleiche Vorstellung von einem zu implementierenden und dann zu testenden Usecase haben. +
Stolz bin ich darauf, dass wir das umsetzen konnten, was von der Kundin gefordert und erwartet wurde, sodass die Arbeit der Kundin durch die entwickelte Software vereinfacht und effizient unterstützt wird. Vor allem konnten wir im Großen und Ganzen das umsetzen, was wir uns selbst vorgenommen hatten. Positiv empfinde ich außerdem, wie wir unter den besonderen Umständen in diesem Semester wieder an das gemeinsame Arbeiten gekommen sind und die vorgegebenen Abläufe trotz Wegfall von persönlichen Meetings insgesamt sehr gut umsetzen und organisieren konnten. Ich denke, das ist der wichtigste Aspekt dieses Projektes und des gesamten Beleges und das worum es hauptsächlich ging. Schade empfinde ich, dass mal wieder deutlich wurde, welche Rolle das Ego spielt. Nicht innerhalb vom Team, sondern bezogen auf die Kommunikation mit anderen Teams. Da ging es kaum darum, wie man etwas macht und den Austausch darüber, was der eigentliche Schwerpunkt dieses Beleges ist, sondern was man macht und welches Projekt nun größer und anspruchsvoller ist oder wie viel man schafft umzusetzen und so weiter. Da hätte man sich meiner Ansicht nach besser auch Teamübergreifend austauschen können. Leider wurde diese Einstellung ebenfalls bei einem der Betreuer selbst während der Präsentation sichtbar, wo ich der Ansicht bin, dass es speziell an der Stelle kein Forum für so etwas ist. Abgesehen davon, dass es generell immer der Fall sein sollte, dass Betreuer sich da neutral und sachlich verhalten. +
Gut funktioniert hat die Oraganisation und Kommunikation im Team. Sowohl in der Zeit als Präsenztermine möglich waren, als auch bei den Meetings online haben wir es mehrheitlich geschafft, auf das wesentliche reduzierte Meetings abzuhalten, in denen alles geklärt wurde. Die Abstimmung unter den einzelnen Rollen funktionierte dabei reibungslos. Dies wurde insbesondere durch die Arbeit mit Github Issues unterstützt, da direkt Arbeit zugewiesen werden konnte, wenn eine Vorarbeit erledigt wurde. Auch die Behebung von erkannten Abweichungen erfolgte sehr schnell. Ebenfalls gut funktioniert hat die Arbeit mit Python als Programmiersprache. Obwohl der Großteil des Teams vor dem Projekt keine Erfarhnung mit Python hatte, war es die richtige Entscheidung, eine für die meisten von uns neue Sprache zu wählen, um auch auf diesem Wege die Fähigkeiten zu erweitern. +
Im nächsten Projekt würde ich die Oragnisation der Dokumente von Beginn an in der Art handhaben, wie es jetzt zum Ende der Fall ist. Da ging schon etwas Zeit drauf, die Sachen ein paar mal umzuorganisieren und vor allem erstmal die Struktur der einzelnen Workproducts zu durchblicken. Generell wäre es auch wünschenswert gewesen, vor dem Projekt oder zumindest zu einem früheren Zeitpunkt schon mehr Kenntnisse über das Testen von Software zu haben. Das sollte man eigentlich auch schon in einem der Fächer Programmieren lernen.