
#include "nuitka/prelude.h"
#include "structseq.h"

// Sentinel PyObject to be used for all our call iterator endings. It will
// become a PyCObject pointing to NULL. It's address is unique, and that's
// enough for us to use it as sentinel value.
PyObject *_sentinel_value = NULL;

PyObject *Nuitka_dunder_compiled_value = NULL;

PyObject *const_int_0;
PyObject *const_str_dot;
PyObject *const_float_0_0;
PyObject *const_float_1_0;
PyObject *const_int_neg_1;
PyObject *const_int_neg_2;
PyObject *const_int_neg_3;
PyObject *const_int_pos_1;
PyObject *const_int_pos_2;
PyObject *const_int_pos_3;
PyObject *const_int_pos_4;
PyObject *const_str_empty;
PyObject *const_str_space;
PyObject *const_dict_empty;
PyObject *const_str_chr_34;
PyObject *const_str_chr_44;
PyObject *const_str_chr_58;
PyObject *const_str_chr_92;
PyObject *const_bytes_empty;
PyObject *const_str_chr_124;
PyObject *const_str_plain__;
PyObject *const_str_plain_a;
PyObject *const_str_plain_s;
PyObject *const_str_plain_w;
PyObject *const_str_plain_x;
PyObject *const_tuple_empty;
PyObject *const_str_plain_Qt;
PyObject *const_str_plain_os;
PyObject *const_str_plain_rb;
PyObject *const_str_plain_re;
PyObject *const_str_plain_ui;
PyObject *const_str_plain_cls;
PyObject *const_str_plain_end;
PyObject *const_str_plain_get;
PyObject *const_str_plain_idx;
PyObject *const_str_plain_int;
PyObject *const_str_plain_len;
PyObject *const_str_plain_map;
PyObject *const_str_plain_obj;
PyObject *const_str_plain_str;
PyObject *const_str_plain_sub;
PyObject *const_str_plain_sum;
PyObject *const_str_plain_sys;
PyObject *const_str_plain_tag;
PyObject *const_str_plain_uic;
PyObject *const_str_plain_Line;
PyObject *const_str_plain_None;
PyObject *const_str_plain_PATH;
PyObject *const_str_plain_args;
PyObject *const_str_plain_dict;
PyObject *const_str_plain_elem;
PyObject *const_str_plain_exec;
PyObject *const_str_plain_file;
PyObject *const_str_plain_font;
PyObject *const_str_plain_icon;
PyObject *const_str_plain_item;
PyObject *const_str_plain_iter;
PyObject *const_str_plain_join;
PyObject *const_str_plain_keys;
PyObject *const_str_plain_misc;
PyObject *const_str_plain_name;
PyObject *const_str_plain_open;
PyObject *const_str_plain_part;
PyObject *const_str_plain_path;
PyObject *const_str_plain_prop;
PyObject *const_str_plain_r_op;
PyObject *const_str_plain_read;
PyObject *const_str_plain_repr;
PyObject *const_str_plain_role;
PyObject *const_str_plain_root;
PyObject *const_str_plain_self;
PyObject *const_str_plain_send;
PyObject *const_str_plain_site;
PyObject *const_str_plain_slot;
PyObject *const_str_plain_text;
PyObject *const_str_plain_type;
PyObject *const_str_plain_vert;
PyObject *const_float_minus_0_0;
PyObject *const_float_minus_1_0;
PyObject *const_str_plain_DEBUG;
PyObject *const_str_plain_False;
PyObject *const_str_plain_PyQt5;
PyObject *const_str_plain_QFont;
PyObject *const_str_plain_QIcon;
PyObject *const_str_plain_QMenu;
PyObject *const_str_plain_QtGui;
PyObject *const_str_plain_buddy;
PyObject *const_str_plain_bytes;
PyObject *const_str_plain_child;
PyObject *const_str_plain_class;
PyObject *const_str_plain_close;
PyObject *const_str_plain_debug;
PyObject *const_str_plain_flags;
PyObject *const_str_plain_fname;
PyObject *const_str_plain_horiz;
PyObject *const_str_plain_index;
PyObject *const_str_plain_isabs;
PyObject *const_str_plain_items;
PyObject *const_str_plain_level;
PyObject *const_str_plain_lower;
PyObject *const_str_plain_mname;
PyObject *const_str_plain_other;
PyObject *const_str_plain_parse;
PyObject *const_str_plain_print;
PyObject *const_str_plain_proxy;
PyObject *const_str_plain_range;
PyObject *const_str_plain_reset;
PyObject *const_str_plain_rname;
PyObject *const_str_plain_split;
PyObject *const_str_plain_throw;
PyObject *const_str_plain_title;
PyObject *const_str_plain_tuple;
PyObject *const_str_plain_types;
PyObject *const_str_plain_value;
PyObject *const_str_plain_write;
PyObject *const_int_pos_50331648;
PyObject *const_str_angle_lambda;
PyObject *const_str_angle_string;
PyObject *const_str_plain_QBrush;
PyObject *const_str_plain_QFrame;
PyObject *const_str_plain_QtCore;
PyObject *const_str_plain___eq__;
PyObject *const_str_plain___or__;
PyObject *const_str_plain_addTab;
PyObject *const_str_plain_append;
PyObject *const_str_plain_attrib;
PyObject *const_str_plain_dedent;
PyObject *const_str_plain_format;
PyObject *const_str_plain_header;
PyObject *const_str_plain_indent;
PyObject *const_str_plain_invoke;
PyObject *const_str_plain_isfile;
PyObject *const_str_plain_layout;
PyObject *const_str_plain_loadUi;
PyObject *const_str_plain_locals;
PyObject *const_str_plain_logger;
PyObject *const_str_plain_margin;
PyObject *const_str_plain_method;
PyObject *const_str_plain_module;
PyObject *const_str_plain_object;
PyObject *const_str_plain_origin;
PyObject *const_str_plain_search;
PyObject *const_str_plain_sender;
PyObject *const_str_plain_string;
PyObject *const_str_plain_uiname;
PyObject *const_str_plain_values;
PyObject *const_str_plain_widget;
PyObject *const_tuple_true_tuple;
PyObject *const_str_plain_Literal;
PyObject *const_str_plain_QAction;
PyObject *const_str_plain_QLayout;
PyObject *const_str_plain_QPixmap;
PyObject *const_str_plain_QWidget;
PyObject *const_str_plain_QWizard;
PyObject *const_str_plain___all__;
PyObject *const_str_plain___cmp__;
PyObject *const_str_plain___doc__;
PyObject *const_str_plain___str__;
PyObject *const_str_plain__escape;
PyObject *const_str_plain__module;
PyObject *const_str_plain_addItem;
PyObject *const_str_plain_buddies;
PyObject *const_str_plain_classes;
PyObject *const_str_plain_clsname;
PyObject *const_str_plain_compile;
PyObject *const_str_plain_connect;
PyObject *const_str_plain_context;
PyObject *const_str_plain_convert;
PyObject *const_str_plain_dirname;
PyObject *const_str_plain_environ;
PyObject *const_str_plain_factory;
PyObject *const_str_plain_findall;
PyObject *const_str_plain_getSlot;
PyObject *const_str_plain_globals;
PyObject *const_str_plain_indexOf;
PyObject *const_str_plain_inspect;
PyObject *const_str_plain_listdir;
PyObject *const_str_plain_logging;
PyObject *const_str_plain_package;
PyObject *const_str_plain_replace;
PyObject *const_str_plain_spacing;
PyObject *const_str_plain_uiclass;
PyObject *const_str_angle_listcomp;
PyObject *const_str_plain_Compiler;
PyObject *const_str_plain_QMdiArea;
PyObject *const_str_plain_QMenuBar;
PyObject *const_str_plain_QPalette;
PyObject *const_str_plain_QToolBar;
PyObject *const_str_plain_QToolBox;
PyObject *const_str_plain_StringIO;
PyObject *const_str_plain_UIParser;
PyObject *const_str_plain___dict__;
PyObject *const_str_plain___exit__;
PyObject *const_str_plain___file__;
PyObject *const_str_plain___init__;
PyObject *const_str_plain___iter__;
PyObject *const_str_plain___main__;
PyObject *const_str_plain___name__;
PyObject *const_str_plain___path__;
PyObject *const_str_plain___spec__;
PyObject *const_str_plain__classes;
PyObject *const_str_plain__cpolicy;
PyObject *const_str_plain__modules;
PyObject *const_str_plain__package;
PyObject *const_str_plain__widgets;
PyObject *const_str_plain_asString;
PyObject *const_str_plain_base_dir;
PyObject *const_str_plain_disambig;
PyObject *const_str_plain_endswith;
PyObject *const_str_plain_filename;
PyObject *const_str_plain_finalize;
PyObject *const_str_plain_findtext;
PyObject *const_str_plain_fromlist;
PyObject *const_str_plain_get_icon;
PyObject *const_str_plain_indenter;
PyObject *const_str_plain_property;
PyObject *const_str_plain_slotname;
PyObject *const_str_plain_uiparser;
PyObject *const_str_plain_viewport;
PyObject *const_str_angle_metaclass;
PyObject *const_str_plain_IconCache;
PyObject *const_str_plain_ProxyBase;
PyObject *const_str_plain_QComboBox;
PyObject *const_str_plain_QTreeView;
PyObject *const_str_plain_QtWidgets;
PyObject *const_str_plain___class__;
PyObject *const_str_plain___debug__;
PyObject *const_str_plain___enter__;
PyObject *const_str_plain__base_dir;
PyObject *const_str_plain_as_string;
PyObject *const_str_plain_attribute;
PyObject *const_str_plain_baseClass;
PyObject *const_str_plain_baseclass;
PyObject *const_str_plain_bytearray;
PyObject *const_str_plain_className;
PyObject *const_str_plain_classname;
PyObject *const_str_plain_clsObject;
PyObject *const_str_plain_compileUi;
PyObject *const_str_plain_ctor_args;
PyObject *const_str_plain_enumerate;
PyObject *const_str_plain_getLogger;
PyObject *const_str_plain_maketrans;
PyObject *const_str_plain_metaclass;
PyObject *const_str_plain_qtproxies;
PyObject *const_str_plain_resources;
PyObject *const_str_plain_topMargin;
PyObject *const_str_plain_translate;
PyObject *const_tuple_str_dot_tuple;
PyObject *const_str_plain_Properties;
PyObject *const_str_plain_QBoxLayout;
PyObject *const_str_plain_QStatusBar;
PyObject *const_str_plain_QTabWidget;
PyObject *const_str_plain_QTableView;
PyObject *const_str_plain_UICompiler;
PyObject *const_str_plain__QtWrapper;
PyObject *const_str_plain___cached__;
PyObject *const_str_plain___import__;
PyObject *const_str_plain___loader__;
PyObject *const_str_plain___module__;
PyObject *const_str_plain__esc_regex;
PyObject *const_str_plain_exceptions;
PyObject *const_str_plain_headerItem;
PyObject *const_str_plain_hexversion;
PyObject *const_str_plain_leftMargin;
PyObject *const_str_plain_menuAction;
PyObject *const_str_plain_metaObject;
PyObject *const_str_plain_objcreator;
PyObject *const_str_plain_objectName;
PyObject *const_str_plain_objectname;
PyObject *const_str_plain_properties;
PyObject *const_str_plain_setContext;
PyObject *const_str_plain_sizePolicy;
PyObject *const_str_plain_startswith;
PyObject *const_str_plain_widgetname;
PyObject *const_str_plain_write_code;
PyObject *const_str_plain_QDockWidget;
PyObject *const_str_plain_QFormLayout;
PyObject *const_str_plain_QGridLayout;
PyObject *const_str_plain_QListWidget;
PyObject *const_str_plain_QMainWindow;
PyObject *const_str_plain_QMetaObject;
PyObject *const_str_plain_QPushButton;
PyObject *const_str_plain_QScrollArea;
PyObject *const_str_plain_QSizePolicy;
PyObject *const_str_plain_QSpacerItem;
PyObject *const_str_plain_QTreeWidget;
PyObject *const_str_plain___getitem__;
PyObject *const_str_plain___package__;
PyObject *const_str_plain___prepare__;
PyObject *const_str_plain_ascii_upper;
PyObject *const_str_plain_classmethod;
PyObject *const_str_plain_getIndenter;
PyObject *const_str_plain_getProperty;
PyObject *const_str_plain_import_from;
PyObject *const_str_plain_indentwidth;
PyObject *const_str_plain_instantiate;
PyObject *const_str_plain_orientation;
PyObject *const_str_plain_rightMargin;
PyObject *const_str_plain_setProperty;
PyObject *const_str_plain_signal_name;
PyObject *const_str_plain_widgetClass;
PyObject *const_tuple_str_empty_tuple;
PyObject *const_str_plain_QActionGroup;
PyObject *const_str_plain_QApplication;
PyObject *const_str_plain_QButtonGroup;
PyObject *const_str_plain_QTableWidget;
PyObject *const_str_plain___builtins__;
PyObject *const_str_plain___compiled__;
PyObject *const_str_plain___qualname__;
PyObject *const_str_plain_bottomMargin;
PyObject *const_str_plain_from_imports;
PyObject *const_str_plain_getAttribute;
PyObject *const_str_plain_has_location;
PyObject *const_str_plain_i18n_context;
PyObject *const_str_plain_i18n_strings;
PyObject *const_str_plain_is_attribute;
PyObject *const_str_plain_moduleMember;
PyObject *const_str_plain_pyuicMargins;
PyObject *const_str_plain_pyuicSpacing;
PyObject *const_str_plain_qtgui_module;
PyObject *const_str_plain_set_base_dir;
PyObject *const_str_plain_staticmethod;
PyObject *const_str_plain_topLevelItem;
PyObject *const_str_plain__QtGuiWrapper;
PyObject *const_str_plain___metaclass__;
PyObject *const_str_plain__initializing;
PyObject *const_str_plain_createQObject;
PyObject *const_str_plain_creatorPolicy;
PyObject *const_str_plain_delayed_props;
PyObject *const_str_plain_qtcore_module;
PyObject *const_str_plain_setProperties;
PyObject *const_tuple_str_chr_124_tuple;
PyObject *const_tuple_str_plain_s_tuple;
PyObject *const_tuple_type_object_tuple;
PyObject *const_str_plain_ProxyMetaclass;
PyObject *const_str_plain_QDoubleSpinBox;
PyObject *const_str_plain_QObjectCreator;
PyObject *const_str_plain_QStackedWidget;
PyObject *const_str_plain__ModuleWrapper;
PyObject *const_str_plain___orig_bases__;
PyObject *const_str_plain_qobjectcreator;
PyObject *const_str_plain_strict_getattr;
PyObject *const_str_plain_toplevelWidget;
PyObject *const_str_plain_verticalHeader;
PyObject *const_slice_int_pos_1_none_none;
PyObject *const_slice_none_int_neg_1_none;
PyObject *const_slice_none_int_neg_2_none;
PyObject *const_slice_none_int_neg_3_none;
PyObject *const_str_plain_DynamicUILoader;
PyObject *const_str_plain_QAbstractButton;
PyObject *const_str_plain_QLinearGradient;
PyObject *const_str_plain_QListWidgetItem;
PyObject *const_str_plain_QRadialGradient;
PyObject *const_str_plain_QTreeWidgetItem;
PyObject *const_str_plain___mro_entries__;
PyObject *const_str_plain_addCustomWidget;
PyObject *const_str_plain_findQObjectType;
PyObject *const_str_plain_resource_suffix;
PyObject *const_str_plain_setDelayedProps;
PyObject *const_str_plain_verticalSpacing;
PyObject *const_tuple_str_plain_obj_tuple;
PyObject *const_str_plain_NoSuchClassError;
PyObject *const_str_plain_QConicalGradient;
PyObject *const_str_plain_QTableWidgetItem;
PyObject *const_str_plain___getattribute__;
PyObject *const_str_plain__writeOutImports;
PyObject *const_str_plain_horizontalHeader;
PyObject *const_str_plain_isSortingEnabled;
PyObject *const_str_plain_no_instantiation;
PyObject *const_str_plain_qtwidgets_module;
PyObject *const_str_plain_widgetPluginPath;
PyObject *const_tuple_str_plain_self_tuple;
PyObject *const_str_plain_LiteralProxyClass;
PyObject *const_str_plain_NoSuchWidgetError;
PyObject *const_str_plain_WidgetPluginError;
PyObject *const_str_plain__QtWidgetsWrapper;
PyObject *const_str_plain___class_getitem__;
PyObject *const_str_plain_add_dll_directory;
PyObject *const_str_plain_horizontalSpacing;
PyObject *const_str_plain_setSortingEnabled;
PyObject *const_tuple_str_plain_class_tuple;
PyObject *const_str_plain__ascii_trans_table;
PyObject *const_str_plain_connectSlotsByName;
PyObject *const_str_plain_createCodeIndenter;
PyObject *const_str_plain_verticalHeaderItem;
PyObject *const_tuple_str_plain_string_tuple;
PyObject *const_str_plain_LoaderCreatorPolicy;
PyObject *const_str_plain__CustomWidgetLoader;
PyObject *const_str_plain_createModuleWrapper;
PyObject *const_str_plain_NUITKA_PACKAGE_PyQt5;
PyObject *const_str_plain_createToplevelWidget;
PyObject *const_str_plain_horizontalHeaderItem;
PyObject *const_tuple_str_plain_StringIO_tuple;
PyObject *const_tuple_str_plain_UIParser_tuple;
PyObject *const_tuple_str_plain_property_tuple;
PyObject *const_str_plain_CompilerCreatorPolicy;
PyObject *const_tuple_str_plain___class___tuple;
PyObject *const_tuple_str_plain_as_string_tuple;
PyObject *const_tuple_str_plain_Properties_tuple;
PyObject *const_tuple_str_plain_write_code_tuple;
PyObject *const_str_plain_NUITKA_PACKAGE_PyQt5_uic;
PyObject *const_str_plain_UnsupportedPropertyError;
PyObject *const_str_plain_createCustomWidgetLoader;
PyObject *const_str_plain_createQtGuiWidgetsWrappers;
PyObject *const_str_plain_submodule_search_locations;
PyObject *const_tuple_str_plain_ProxyMetaclass_tuple;
PyObject *const_dict_51eb06cf18b562904cb641f9f5ce3334;
PyObject *const_tuple_str_plain_self_str_plain_s_tuple;
PyObject *const_tuple_str_plain_text_str_plain_x_tuple;
PyObject *const_tuple_str_plain_cls_str_plain_name_tuple;
PyObject *const_tuple_str_plain_self_str_plain_cls_tuple;
PyObject *const_tuple_str_plain_self_str_plain_r_op_tuple;
PyObject *const_tuple_str_plain_self_str_plain_other_tuple;
PyObject *const_str_digest_1c75306b53bdb8e43cd18449de6927ae;
PyObject *const_str_digest_22116dbcc880f5504e969642694bea9a;
PyObject *const_str_digest_25731c733fd74e8333aa29126ce85686;
PyObject *const_str_digest_2fb35f5b371e4357763cfefa063b5165;
PyObject *const_str_digest_2fe71b40974e92f7a4ed2043bfd21fa9;
PyObject *const_str_digest_3114c7847ed30512509505e34fc4f6e0;
PyObject *const_str_digest_35d21bc483d4b284491535cb2e41474a;
PyObject *const_str_digest_45e4dde2057b0bf276d6a84f4c917d27;
PyObject *const_str_digest_4d848f1798a02d9a0d913955a64e8e94;
PyObject *const_str_digest_50c57a23be6c5bc9e9afc5f4ec8bf468;
PyObject *const_str_digest_5bfaf90dbd407b4fc29090c8f6415242;
PyObject *const_str_digest_75fd71b1edada749c2ef7ac810062295;
PyObject *const_str_digest_7cab9bbb3c340249be5d99a622d04956;
PyObject *const_str_digest_7cb7e1a5659547478f12d8fe755efd75;
PyObject *const_str_digest_802d97a8584e66528f40ec5b87c9e84a;
PyObject *const_str_digest_80c859bc51921fcf1a6ab24d69109fda;
PyObject *const_str_digest_8e8dd3afae40897c981713d7a882d373;
PyObject *const_str_digest_9816e8d1552296af90d250823c964059;
PyObject *const_str_digest_a863bf128934a98648a1a5627a88779d;
PyObject *const_str_digest_aa569b191903e6c21604f529898b6160;
PyObject *const_str_digest_adc474dd61fbd736d69c1bac5d9712e0;
PyObject *const_str_digest_c3711bf97707f5fa779b1dcac0e4a551;
PyObject *const_str_digest_c47129e3fed991365e20c0ca6931502e;
PyObject *const_str_digest_cd6755d620aa6bdc1a5e95a35c0b02b9;
PyObject *const_str_digest_db35ab94a03c3cbeb13cbe2a1d728b77;
PyObject *const_str_digest_de4b0c7ad68311153ea2a31151f2e46a;
PyObject *const_str_digest_e33d037633d5a895496c949f1e0a8014;
PyObject *const_str_digest_e399ba4554180f37de594a6743234f17;
PyObject *const_str_digest_e6450f8c3c0bf1e0c454eba7478ed0c8;
PyObject *const_str_digest_ebebb18731664a12452b2ba6915b22ed;
PyObject *const_str_digest_fbe37053f75eff4f1e91e745af595cf5;
PyObject *const_tuple_2bf0a0f73a15cf1f5a5aa16b99dd5ec6_tuple;
PyObject *const_tuple_3f2f177cbcd58a6e2810b9361003d74a_tuple;
PyObject *const_tuple_8b1fd1016da3eaee3145814dfe4be59a_tuple;
PyObject *const_tuple_ea9a58e3c182e55994a2e18312eb11df_tuple;
PyObject *const_tuple_str_plain_self_str_plain_context_tuple;
PyObject *const_tuple_str_plain_self_str_plain_package_tuple;
PyObject *const_tuple_str_plain_self_str_plain_base_dir_tuple;
PyObject *const_tuple_str_plain_Literal_str_plain_moduleMember_tuple;
PyObject *const_tuple_str_digest_50c57a23be6c5bc9e9afc5f4ec8bf468_tuple;
PyObject *const_tuple_str_digest_ebebb18731664a12452b2ba6915b22ed_tuple;
PyObject *const_tuple_anon_function_anon_builtin_function_or_method_tuple;
PyObject *const_tuple_str_plain_self_str_plain_object_str_plain_slotname_tuple;
PyObject *const_tuple_str_chr_92_str_digest_7cb7e1a5659547478f12d8fe755efd75_tuple;
PyObject *const_tuple_str_plain_self_str_plain_classname_str_plain_widgetname_tuple;

static void _createGlobalConstants(void) {
    NUITKA_MAY_BE_UNUSED PyObject *exception_type, *exception_value;
    NUITKA_MAY_BE_UNUSED PyTracebackObject *exception_tb;

#ifdef _MSC_VER
    // Prevent unused warnings in case of simple programs, the attribute
    // NUITKA_MAY_BE_UNUSED doesn't work for MSVC.
    (void *)exception_type; (void *)exception_value; (void *)exception_tb;
#endif

    const_int_0 = PyLong_FromUnsignedLong(0ul);
    const_str_dot = UNSTREAM_STRING_ASCII(&constant_bin[ 4123 ], 1, 0);
    const_float_0_0 = UNSTREAM_FLOAT(&constant_bin[ 24862 ]);
    const_float_1_0 = UNSTREAM_FLOAT(&constant_bin[ 24870 ]);
    const_int_neg_1 = PyLong_FromLong(-1l);
    const_int_neg_2 = PyLong_FromLong(-2l);
    const_int_neg_3 = PyLong_FromLong(-3l);
    const_int_pos_1 = PyLong_FromUnsignedLong(1ul);
    const_int_pos_2 = PyLong_FromUnsignedLong(2ul);
    const_int_pos_3 = PyLong_FromUnsignedLong(3ul);
    const_int_pos_4 = PyLong_FromUnsignedLong(4ul);
    const_str_empty = UNSTREAM_STRING_ASCII(&constant_bin[ 0 ], 0, 0);
    const_str_space = UNSTREAM_STRING_ASCII(&constant_bin[ 4 ], 1, 0);
    const_dict_empty = _PyDict_NewPresized( 0 );
    assert(PyDict_Size(const_dict_empty) == 0);
    const_str_chr_34 = UNSTREAM_STRING_ASCII(&constant_bin[ 4295 ], 1, 0);
    const_str_chr_44 = UNSTREAM_STRING_ASCII(&constant_bin[ 4776 ], 1, 0);
    const_str_chr_58 = UNSTREAM_STRING_ASCII(&constant_bin[ 4305 ], 1, 0);
    const_str_chr_92 = UNSTREAM_STRING_ASCII(&constant_bin[ 4115 ], 1, 0);
    const_bytes_empty = UNSTREAM_BYTES(&constant_bin[ 0 ], 0);
    const_str_chr_124 = UNSTREAM_STRING_ASCII(&constant_bin[ 24878 ], 1, 0);
    const_str_plain__ = UNSTREAM_STRING_ASCII(&constant_bin[ 6 ], 1, 1);
    const_str_plain_a = UNSTREAM_STRING_ASCII(&constant_bin[ 1 ], 1, 1);
    const_str_plain_s = UNSTREAM_STRING_ASCII(&constant_bin[ 17 ], 1, 1);
    const_str_plain_w = UNSTREAM_STRING_ASCII(&constant_bin[ 357 ], 1, 1);
    const_str_plain_x = UNSTREAM_STRING_ASCII(&constant_bin[ 255 ], 1, 1);
    const_tuple_empty = PyTuple_New(0);
    const_str_plain_Qt = UNSTREAM_STRING_ASCII(&constant_bin[ 669 ], 2, 1);
    const_str_plain_os = UNSTREAM_STRING_ASCII(&constant_bin[ 2350 ], 2, 1);
    const_str_plain_rb = UNSTREAM_STRING_ASCII(&constant_bin[ 14882 ], 2, 1);
    const_str_plain_re = UNSTREAM_STRING_ASCII(&constant_bin[ 290 ], 2, 1);
    const_str_plain_ui = UNSTREAM_STRING_ASCII(&constant_bin[ 731 ], 2, 1);
    const_str_plain_cls = UNSTREAM_STRING_ASCII(&constant_bin[ 24879 ], 3, 1);
    const_str_plain_end = UNSTREAM_STRING_ASCII(&constant_bin[ 5218 ], 3, 1);
    const_str_plain_get = UNSTREAM_STRING_ASCII(&constant_bin[ 324 ], 3, 1);
    const_str_plain_idx = UNSTREAM_STRING_ASCII(&constant_bin[ 24882 ], 3, 1);
    const_str_plain_int = UNSTREAM_STRING_ASCII(&constant_bin[ 1096 ], 3, 1);
    const_str_plain_len = UNSTREAM_STRING_ASCII(&constant_bin[ 11334 ], 3, 1);
    const_str_plain_map = UNSTREAM_STRING_ASCII(&constant_bin[ 6647 ], 3, 1);
    const_str_plain_obj = UNSTREAM_STRING_ASCII(&constant_bin[ 5002 ], 3, 1);
    const_str_plain_str = UNSTREAM_STRING_ASCII(&constant_bin[ 633 ], 3, 1);
    const_str_plain_sub = UNSTREAM_STRING_ASCII(&constant_bin[ 6978 ], 3, 1);
    const_str_plain_sum = UNSTREAM_STRING_ASCII(&constant_bin[ 24885 ], 3, 1);
    const_str_plain_sys = UNSTREAM_STRING_ASCII(&constant_bin[ 909 ], 3, 1);
    const_str_plain_tag = UNSTREAM_STRING_ASCII(&constant_bin[ 15817 ], 3, 1);
    const_str_plain_uic = UNSTREAM_STRING_ASCII(&constant_bin[ 3893 ], 3, 1);
    const_str_plain_Line = UNSTREAM_STRING_ASCII(&constant_bin[ 10870 ], 4, 1);
    const_str_plain_None = UNSTREAM_STRING_ASCII(&constant_bin[ 5694 ], 4, 1);
    const_str_plain_PATH = UNSTREAM_STRING_ASCII(&constant_bin[ 24888 ], 4, 1);
    const_str_plain_args = UNSTREAM_STRING_ASCII(&constant_bin[ 4244 ], 4, 1);
    const_str_plain_dict = UNSTREAM_STRING_ASCII(&constant_bin[ 24892 ], 4, 1);
    const_str_plain_elem = UNSTREAM_STRING_ASCII(&constant_bin[ 18901 ], 4, 1);
    const_str_plain_exec = UNSTREAM_STRING_ASCII(&constant_bin[ 4183 ], 4, 1);
    const_str_plain_file = UNSTREAM_STRING_ASCII(&constant_bin[ 8 ], 4, 1);
    const_str_plain_font = UNSTREAM_STRING_ASCII(&constant_bin[ 3153 ], 4, 1);
    const_str_plain_icon = UNSTREAM_STRING_ASCII(&constant_bin[ 15517 ], 4, 1);
    const_str_plain_item = UNSTREAM_STRING_ASCII(&constant_bin[ 13187 ], 4, 1);
    const_str_plain_iter = UNSTREAM_STRING_ASCII(&constant_bin[ 477 ], 4, 1);
    const_str_plain_join = UNSTREAM_STRING_ASCII(&constant_bin[ 24896 ], 4, 1);
    const_str_plain_keys = UNSTREAM_STRING_ASCII(&constant_bin[ 24900 ], 4, 1);
    const_str_plain_misc = UNSTREAM_STRING_ASCII(&constant_bin[ 9608 ], 4, 1);
    const_str_plain_name = UNSTREAM_STRING_ASCII(&constant_bin[ 0 ], 4, 1);
    const_str_plain_open = UNSTREAM_STRING_ASCII(&constant_bin[ 24904 ], 4, 1);
    const_str_plain_part = UNSTREAM_STRING_ASCII(&constant_bin[ 16474 ], 4, 1);
    const_str_plain_path = UNSTREAM_STRING_ASCII(&constant_bin[ 4266 ], 4, 1);
    const_str_plain_prop = UNSTREAM_STRING_ASCII(&constant_bin[ 3193 ], 4, 1);
    const_str_plain_r_op = UNSTREAM_STRING_ASCII(&constant_bin[ 24908 ], 4, 1);
    const_str_plain_read = UNSTREAM_STRING_ASCII(&constant_bin[ 4561 ], 4, 1);
    const_str_plain_repr = UNSTREAM_STRING_ASCII(&constant_bin[ 24912 ], 4, 1);
    const_str_plain_role = UNSTREAM_STRING_ASCII(&constant_bin[ 16134 ], 4, 1);
    const_str_plain_root = UNSTREAM_STRING_ASCII(&constant_bin[ 23078 ], 4, 1);
    const_str_plain_self = UNSTREAM_STRING_ASCII(&constant_bin[ 8858 ], 4, 1);
    const_str_plain_send = UNSTREAM_STRING_ASCII(&constant_bin[ 14170 ], 4, 1);
    const_str_plain_site = UNSTREAM_STRING_ASCII(&constant_bin[ 3943 ], 4, 1);
    const_str_plain_slot = UNSTREAM_STRING_ASCII(&constant_bin[ 24916 ], 4, 1);
    const_str_plain_text = UNSTREAM_STRING_ASCII(&constant_bin[ 1168 ], 4, 1);
    const_str_plain_type = UNSTREAM_STRING_ASCII(&constant_bin[ 2253 ], 4, 1);
    const_str_plain_vert = UNSTREAM_STRING_ASCII(&constant_bin[ 13140 ], 4, 1);
    const_float_minus_0_0 = UNSTREAM_FLOAT(&constant_bin[ 24920 ]);
    const_float_minus_1_0 = UNSTREAM_FLOAT(&constant_bin[ 24928 ]);
    const_str_plain_DEBUG = UNSTREAM_STRING_ASCII(&constant_bin[ 700 ], 5, 1);
    const_str_plain_False = UNSTREAM_STRING_ASCII(&constant_bin[ 4791 ], 5, 1);
    const_str_plain_PyQt5 = UNSTREAM_STRING_ASCII(&constant_bin[ 4135 ], 5, 1);
    const_str_plain_QFont = UNSTREAM_STRING_ASCII(&constant_bin[ 11346 ], 5, 1);
    const_str_plain_QIcon = UNSTREAM_STRING_ASCII(&constant_bin[ 11008 ], 5, 1);
    const_str_plain_QMenu = UNSTREAM_STRING_ASCII(&constant_bin[ 13258 ], 5, 1);
    const_str_plain_QtGui = UNSTREAM_STRING_ASCII(&constant_bin[ 728 ], 5, 1);
    const_str_plain_buddy = UNSTREAM_STRING_ASCII(&constant_bin[ 17987 ], 5, 1);
    const_str_plain_bytes = UNSTREAM_STRING_ASCII(&constant_bin[ 24936 ], 5, 1);
    const_str_plain_child = UNSTREAM_STRING_ASCII(&constant_bin[ 12966 ], 5, 1);
    const_str_plain_class = UNSTREAM_STRING_ASCII(&constant_bin[ 572 ], 5, 1);
    const_str_plain_close = UNSTREAM_STRING_ASCII(&constant_bin[ 24941 ], 5, 1);
    const_str_plain_debug = UNSTREAM_STRING_ASCII(&constant_bin[ 24946 ], 5, 1);
    const_str_plain_flags = UNSTREAM_STRING_ASCII(&constant_bin[ 21092 ], 5, 1);
    const_str_plain_fname = UNSTREAM_STRING_ASCII(&constant_bin[ 4722 ], 5, 1);
    const_str_plain_horiz = UNSTREAM_STRING_ASCII(&constant_bin[ 13417 ], 5, 1);
    const_str_plain_index = UNSTREAM_STRING_ASCII(&constant_bin[ 10681 ], 5, 1);
    const_str_plain_isabs = UNSTREAM_STRING_ASCII(&constant_bin[ 24951 ], 5, 1);
    const_str_plain_items = UNSTREAM_STRING_ASCII(&constant_bin[ 20500 ], 5, 1);
    const_str_plain_level = UNSTREAM_STRING_ASCII(&constant_bin[ 3969 ], 5, 1);
    const_str_plain_lower = UNSTREAM_STRING_ASCII(&constant_bin[ 17023 ], 5, 1);
    const_str_plain_mname = UNSTREAM_STRING_ASCII(&constant_bin[ 24956 ], 5, 1);
    const_str_plain_other = UNSTREAM_STRING_ASCII(&constant_bin[ 24961 ], 5, 1);
    const_str_plain_parse = UNSTREAM_STRING_ASCII(&constant_bin[ 3293 ], 5, 1);
    const_str_plain_print = UNSTREAM_STRING_ASCII(&constant_bin[ 1094 ], 5, 1);
    const_str_plain_proxy = UNSTREAM_STRING_ASCII(&constant_bin[ 9689 ], 5, 1);
    const_str_plain_range = UNSTREAM_STRING_ASCII(&constant_bin[ 24966 ], 5, 1);
    const_str_plain_reset = UNSTREAM_STRING_ASCII(&constant_bin[ 9277 ], 5, 1);
    const_str_plain_rname = UNSTREAM_STRING_ASCII(&constant_bin[ 18688 ], 5, 1);
    const_str_plain_split = UNSTREAM_STRING_ASCII(&constant_bin[ 24971 ], 5, 1);
    const_str_plain_throw = UNSTREAM_STRING_ASCII(&constant_bin[ 24976 ], 5, 1);
    const_str_plain_title = UNSTREAM_STRING_ASCII(&constant_bin[ 24981 ], 5, 1);
    const_str_plain_tuple = UNSTREAM_STRING_ASCII(&constant_bin[ 7233 ], 5, 1);
    const_str_plain_types = UNSTREAM_STRING_ASCII(&constant_bin[ 24986 ], 5, 1);
    const_str_plain_value = UNSTREAM_STRING_ASCII(&constant_bin[ 6602 ], 5, 1);
    const_str_plain_write = UNSTREAM_STRING_ASCII(&constant_bin[ 357 ], 5, 1);
    const_int_pos_50331648 = PyLong_FromUnsignedLong(50331648ul);
    const_str_angle_lambda = UNSTREAM_STRING_ASCII(&constant_bin[ 19350 ], 8, 0);
    const_str_angle_string = UNSTREAM_STRING_ASCII(&constant_bin[ 24991 ], 8, 0);
    const_str_plain_QBrush = UNSTREAM_STRING_ASCII(&constant_bin[ 13474 ], 6, 1);
    const_str_plain_QFrame = UNSTREAM_STRING_ASCII(&constant_bin[ 1796 ], 6, 1);
    const_str_plain_QtCore = UNSTREAM_STRING_ASCII(&constant_bin[ 1474 ], 6, 1);
    const_str_plain___eq__ = UNSTREAM_STRING_ASCII(&constant_bin[ 9977 ], 6, 1);
    const_str_plain___or__ = UNSTREAM_STRING_ASCII(&constant_bin[ 9475 ], 6, 1);
    const_str_plain_addTab = UNSTREAM_STRING_ASCII(&constant_bin[ 11422 ], 6, 1);
    const_str_plain_append = UNSTREAM_STRING_ASCII(&constant_bin[ 5215 ], 6, 1);
    const_str_plain_attrib = UNSTREAM_STRING_ASCII(&constant_bin[ 10003 ], 6, 1);
    const_str_plain_dedent = UNSTREAM_STRING_ASCII(&constant_bin[ 9302 ], 6, 1);
    const_str_plain_format = UNSTREAM_STRING_ASCII(&constant_bin[ 16759 ], 6, 1);
    const_str_plain_header = UNSTREAM_STRING_ASCII(&constant_bin[ 127 ], 6, 1);
    const_str_plain_indent = UNSTREAM_STRING_ASCII(&constant_bin[ 96 ], 6, 1);
    const_str_plain_invoke = UNSTREAM_STRING_ASCII(&constant_bin[ 10484 ], 6, 1);
    const_str_plain_isfile = UNSTREAM_STRING_ASCII(&constant_bin[ 24999 ], 6, 1);
    const_str_plain_layout = UNSTREAM_STRING_ASCII(&constant_bin[ 3497 ], 6, 1);
    const_str_plain_loadUi = UNSTREAM_STRING_ASCII(&constant_bin[ 4759 ], 6, 1);
    const_str_plain_locals = UNSTREAM_STRING_ASCII(&constant_bin[ 2225 ], 6, 1);
    const_str_plain_logger = UNSTREAM_STRING_ASCII(&constant_bin[ 25005 ], 6, 1);
    const_str_plain_margin = UNSTREAM_STRING_ASCII(&constant_bin[ 25011 ], 6, 1);
    const_str_plain_method = UNSTREAM_STRING_ASCII(&constant_bin[ 968 ], 6, 1);
    const_str_plain_module = UNSTREAM_STRING_ASCII(&constant_bin[ 599 ], 6, 1);
    const_str_plain_object = UNSTREAM_STRING_ASCII(&constant_bin[ 5002 ], 6, 1);
    const_str_plain_origin = UNSTREAM_STRING_ASCII(&constant_bin[ 25017 ], 6, 1);
    const_str_plain_search = UNSTREAM_STRING_ASCII(&constant_bin[ 25023 ], 6, 1);
    const_str_plain_sender = UNSTREAM_STRING_ASCII(&constant_bin[ 14170 ], 6, 1);
    const_str_plain_string = UNSTREAM_STRING_ASCII(&constant_bin[ 881 ], 6, 1);
    const_str_plain_uiname = UNSTREAM_STRING_ASCII(&constant_bin[ 24047 ], 6, 1);
    const_str_plain_values = UNSTREAM_STRING_ASCII(&constant_bin[ 25029 ], 6, 1);
    const_str_plain_widget = UNSTREAM_STRING_ASCII(&constant_bin[ 2168 ], 6, 1);
    const_tuple_true_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_true_tuple, 0, Py_True); Py_INCREF(Py_True);
    const_str_plain_Literal = UNSTREAM_STRING_ASCII(&constant_bin[ 534 ], 7, 1);
    const_str_plain_QAction = UNSTREAM_STRING_ASCII(&constant_bin[ 11389 ], 7, 1);
    const_str_plain_QLayout = UNSTREAM_STRING_ASCII(&constant_bin[ 1536 ], 7, 1);
    const_str_plain_QPixmap = UNSTREAM_STRING_ASCII(&constant_bin[ 25035 ], 7, 1);
    const_str_plain_QWidget = UNSTREAM_STRING_ASCII(&constant_bin[ 1597 ], 7, 1);
    const_str_plain_QWizard = UNSTREAM_STRING_ASCII(&constant_bin[ 13777 ], 7, 1);
    const_str_plain___all__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25042 ], 7, 1);
    const_str_plain___cmp__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25049 ], 7, 1);
    const_str_plain___doc__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25056 ], 7, 1);
    const_str_plain___str__ = UNSTREAM_STRING_ASCII(&constant_bin[ 9678 ], 7, 1);
    const_str_plain__escape = UNSTREAM_STRING_ASCII(&constant_bin[ 2638 ], 7, 1);
    const_str_plain__module = UNSTREAM_STRING_ASCII(&constant_bin[ 15190 ], 7, 1);
    const_str_plain_addItem = UNSTREAM_STRING_ASCII(&constant_bin[ 12615 ], 7, 1);
    const_str_plain_buddies = UNSTREAM_STRING_ASCII(&constant_bin[ 25063 ], 7, 1);
    const_str_plain_classes = UNSTREAM_STRING_ASCII(&constant_bin[ 25070 ], 7, 1);
    const_str_plain_clsname = UNSTREAM_STRING_ASCII(&constant_bin[ 25077 ], 7, 1);
    const_str_plain_compile = UNSTREAM_STRING_ASCII(&constant_bin[ 65 ], 7, 1);
    const_str_plain_connect = UNSTREAM_STRING_ASCII(&constant_bin[ 11156 ], 7, 1);
    const_str_plain_context = UNSTREAM_STRING_ASCII(&constant_bin[ 1165 ], 7, 1);
    const_str_plain_convert = UNSTREAM_STRING_ASCII(&constant_bin[ 18017 ], 7, 1);
    const_str_plain_dirname = UNSTREAM_STRING_ASCII(&constant_bin[ 25084 ], 7, 1);
    const_str_plain_environ = UNSTREAM_STRING_ASCII(&constant_bin[ 25091 ], 7, 1);
    const_str_plain_factory = UNSTREAM_STRING_ASCII(&constant_bin[ 15984 ], 7, 1);
    const_str_plain_findall = UNSTREAM_STRING_ASCII(&constant_bin[ 25098 ], 7, 1);
    const_str_plain_getSlot = UNSTREAM_STRING_ASCII(&constant_bin[ 10364 ], 7, 1);
    const_str_plain_globals = UNSTREAM_STRING_ASCII(&constant_bin[ 5642 ], 7, 1);
    const_str_plain_indexOf = UNSTREAM_STRING_ASCII(&constant_bin[ 12273 ], 7, 1);
    const_str_plain_inspect = UNSTREAM_STRING_ASCII(&constant_bin[ 25105 ], 7, 1);
    const_str_plain_listdir = UNSTREAM_STRING_ASCII(&constant_bin[ 25112 ], 7, 1);
    const_str_plain_logging = UNSTREAM_STRING_ASCII(&constant_bin[ 934 ], 7, 1);
    const_str_plain_package = UNSTREAM_STRING_ASCII(&constant_bin[ 4009 ], 7, 1);
    const_str_plain_replace = UNSTREAM_STRING_ASCII(&constant_bin[ 25119 ], 7, 1);
    const_str_plain_spacing = UNSTREAM_STRING_ASCII(&constant_bin[ 25126 ], 7, 1);
    const_str_plain_uiclass = UNSTREAM_STRING_ASCII(&constant_bin[ 4411 ], 7, 1);
    const_str_angle_listcomp = UNSTREAM_STRING_ASCII(&constant_bin[ 25133 ], 10, 0);
    const_str_plain_Compiler = UNSTREAM_STRING_ASCII(&constant_bin[ 281 ], 8, 1);
    const_str_plain_QMdiArea = UNSTREAM_STRING_ASCII(&constant_bin[ 13113 ], 8, 1);
    const_str_plain_QMenuBar = UNSTREAM_STRING_ASCII(&constant_bin[ 25143 ], 8, 1);
    const_str_plain_QPalette = UNSTREAM_STRING_ASCII(&constant_bin[ 12108 ], 8, 1);
    const_str_plain_QToolBar = UNSTREAM_STRING_ASCII(&constant_bin[ 25151 ], 8, 1);
    const_str_plain_QToolBox = UNSTREAM_STRING_ASCII(&constant_bin[ 11619 ], 8, 1);
    const_str_plain_StringIO = UNSTREAM_STRING_ASCII(&constant_bin[ 17269 ], 8, 1);
    const_str_plain_UIParser = UNSTREAM_STRING_ASCII(&constant_bin[ 220 ], 8, 1);
    const_str_plain___dict__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25159 ], 8, 1);
    const_str_plain___exit__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25167 ], 8, 1);
    const_str_plain___file__ = UNSTREAM_STRING_ASCII(&constant_bin[ 6 ], 8, 1);
    const_str_plain___init__ = UNSTREAM_STRING_ASCII(&constant_bin[ 4172 ], 8, 1);
    const_str_plain___iter__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25175 ], 8, 1);
    const_str_plain___main__ = UNSTREAM_STRING_ASCII(&constant_bin[ 4296 ], 8, 1);
    const_str_plain___name__ = UNSTREAM_STRING_ASCII(&constant_bin[ 4283 ], 8, 1);
    const_str_plain___path__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25183 ], 8, 1);
    const_str_plain___spec__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25191 ], 8, 1);
    const_str_plain__classes = UNSTREAM_STRING_ASCII(&constant_bin[ 25199 ], 8, 1);
    const_str_plain__cpolicy = UNSTREAM_STRING_ASCII(&constant_bin[ 25207 ], 8, 1);
    const_str_plain__modules = UNSTREAM_STRING_ASCII(&constant_bin[ 25215 ], 8, 1);
    const_str_plain__package = UNSTREAM_STRING_ASCII(&constant_bin[ 4008 ], 8, 1);
    const_str_plain__widgets = UNSTREAM_STRING_ASCII(&constant_bin[ 25223 ], 8, 1);
    const_str_plain_asString = UNSTREAM_STRING_ASCII(&constant_bin[ 10292 ], 8, 1);
    const_str_plain_base_dir = UNSTREAM_STRING_ASCII(&constant_bin[ 15856 ], 8, 1);
    const_str_plain_disambig = UNSTREAM_STRING_ASCII(&constant_bin[ 25231 ], 8, 1);
    const_str_plain_endswith = UNSTREAM_STRING_ASCII(&constant_bin[ 25239 ], 8, 1);
    const_str_plain_filename = UNSTREAM_STRING_ASCII(&constant_bin[ 15476 ], 8, 1);
    const_str_plain_finalize = UNSTREAM_STRING_ASCII(&constant_bin[ 9254 ], 8, 1);
    const_str_plain_findtext = UNSTREAM_STRING_ASCII(&constant_bin[ 25247 ], 8, 1);
    const_str_plain_fromlist = UNSTREAM_STRING_ASCII(&constant_bin[ 25255 ], 8, 1);
    const_str_plain_get_icon = UNSTREAM_STRING_ASCII(&constant_bin[ 16172 ], 8, 1);
    const_str_plain_indenter = UNSTREAM_STRING_ASCII(&constant_bin[ 96 ], 8, 1);
    const_str_plain_property = UNSTREAM_STRING_ASCII(&constant_bin[ 3193 ], 8, 1);
    const_str_plain_slotname = UNSTREAM_STRING_ASCII(&constant_bin[ 25263 ], 8, 1);
    const_str_plain_uiparser = UNSTREAM_STRING_ASCII(&constant_bin[ 20072 ], 8, 1);
    const_str_plain_viewport = UNSTREAM_STRING_ASCII(&constant_bin[ 11235 ], 8, 1);
    const_str_angle_metaclass = UNSTREAM_STRING_ASCII(&constant_bin[ 25271 ], 11, 0);
    const_str_plain_IconCache = UNSTREAM_STRING_ASCII(&constant_bin[ 2791 ], 9, 1);
    const_str_plain_ProxyBase = UNSTREAM_STRING_ASCII(&constant_bin[ 1375 ], 9, 1);
    const_str_plain_QComboBox = UNSTREAM_STRING_ASCII(&constant_bin[ 1692 ], 9, 1);
    const_str_plain_QTreeView = UNSTREAM_STRING_ASCII(&constant_bin[ 2065 ], 9, 1);
    const_str_plain_QtWidgets = UNSTREAM_STRING_ASCII(&constant_bin[ 669 ], 9, 1);
    const_str_plain___class__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25282 ], 9, 1);
    const_str_plain___debug__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25291 ], 9, 1);
    const_str_plain___enter__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25300 ], 9, 1);
    const_str_plain__base_dir = UNSTREAM_STRING_ASCII(&constant_bin[ 15855 ], 9, 1);
    const_str_plain_as_string = UNSTREAM_STRING_ASCII(&constant_bin[ 878 ], 9, 1);
    const_str_plain_attribute = UNSTREAM_STRING_ASCII(&constant_bin[ 10003 ], 9, 1);
    const_str_plain_baseClass = UNSTREAM_STRING_ASCII(&constant_bin[ 25309 ], 9, 1);
    const_str_plain_baseclass = UNSTREAM_STRING_ASCII(&constant_bin[ 4389 ], 9, 1);
    const_str_plain_bytearray = UNSTREAM_STRING_ASCII(&constant_bin[ 25318 ], 9, 1);
    const_str_plain_className = UNSTREAM_STRING_ASCII(&constant_bin[ 13363 ], 9, 1);
    const_str_plain_classname = UNSTREAM_STRING_ASCII(&constant_bin[ 23584 ], 9, 1);
    const_str_plain_clsObject = UNSTREAM_STRING_ASCII(&constant_bin[ 25327 ], 9, 1);
    const_str_plain_compileUi = UNSTREAM_STRING_ASCII(&constant_bin[ 65 ], 9, 1);
    const_str_plain_ctor_args = UNSTREAM_STRING_ASCII(&constant_bin[ 25336 ], 9, 1);
    const_str_plain_enumerate = UNSTREAM_STRING_ASCII(&constant_bin[ 25345 ], 9, 1);
    const_str_plain_getLogger = UNSTREAM_STRING_ASCII(&constant_bin[ 25354 ], 9, 1);
    const_str_plain_maketrans = UNSTREAM_STRING_ASCII(&constant_bin[ 25363 ], 9, 1);
    const_str_plain_metaclass = UNSTREAM_STRING_ASCII(&constant_bin[ 9826 ], 9, 1);
    const_str_plain_qtproxies = UNSTREAM_STRING_ASCII(&constant_bin[ 250 ], 9, 1);
    const_str_plain_resources = UNSTREAM_STRING_ASCII(&constant_bin[ 8869 ], 9, 1);
    const_str_plain_topMargin = UNSTREAM_STRING_ASCII(&constant_bin[ 25372 ], 9, 1);
    const_str_plain_translate = UNSTREAM_STRING_ASCII(&constant_bin[ 8846 ], 9, 1);
    const_tuple_str_dot_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_dot_tuple, 0, const_str_dot); Py_INCREF(const_str_dot);
    const_str_plain_Properties = UNSTREAM_STRING_ASCII(&constant_bin[ 3366 ], 10, 1);
    const_str_plain_QBoxLayout = UNSTREAM_STRING_ASCII(&constant_bin[ 1565 ], 10, 1);
    const_str_plain_QStatusBar = UNSTREAM_STRING_ASCII(&constant_bin[ 25381 ], 10, 1);
    const_str_plain_QTabWidget = UNSTREAM_STRING_ASCII(&constant_bin[ 11411 ], 10, 1);
    const_str_plain_QTableView = UNSTREAM_STRING_ASCII(&constant_bin[ 2033 ], 10, 1);
    const_str_plain_UICompiler = UNSTREAM_STRING_ASCII(&constant_bin[ 8896 ], 10, 1);
    const_str_plain__QtWrapper = UNSTREAM_STRING_ASCII(&constant_bin[ 996 ], 10, 1);
    const_str_plain___cached__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25391 ], 10, 1);
    const_str_plain___import__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25401 ], 10, 1);
    const_str_plain___loader__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25411 ], 10, 1);
    const_str_plain___module__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25421 ], 10, 1);
    const_str_plain__esc_regex = UNSTREAM_STRING_ASCII(&constant_bin[ 2667 ], 10, 1);
    const_str_plain_exceptions = UNSTREAM_STRING_ASCII(&constant_bin[ 15303 ], 10, 1);
    const_str_plain_headerItem = UNSTREAM_STRING_ASCII(&constant_bin[ 11770 ], 10, 1);
    const_str_plain_hexversion = UNSTREAM_STRING_ASCII(&constant_bin[ 25431 ], 10, 1);
    const_str_plain_leftMargin = UNSTREAM_STRING_ASCII(&constant_bin[ 25441 ], 10, 1);
    const_str_plain_menuAction = UNSTREAM_STRING_ASCII(&constant_bin[ 13264 ], 10, 1);
    const_str_plain_metaObject = UNSTREAM_STRING_ASCII(&constant_bin[ 10721 ], 10, 1);
    const_str_plain_objcreator = UNSTREAM_STRING_ASCII(&constant_bin[ 16440 ], 10, 1);
    const_str_plain_objectName = UNSTREAM_STRING_ASCII(&constant_bin[ 10992 ], 10, 1);
    const_str_plain_objectname = UNSTREAM_STRING_ASCII(&constant_bin[ 25451 ], 10, 1);
    const_str_plain_properties = UNSTREAM_STRING_ASCII(&constant_bin[ 17897 ], 10, 1);
    const_str_plain_setContext = UNSTREAM_STRING_ASCII(&constant_bin[ 9211 ], 10, 1);
    const_str_plain_sizePolicy = UNSTREAM_STRING_ASCII(&constant_bin[ 11431 ], 10, 1);
    const_str_plain_startswith = UNSTREAM_STRING_ASCII(&constant_bin[ 25461 ], 10, 1);
    const_str_plain_widgetname = UNSTREAM_STRING_ASCII(&constant_bin[ 4362 ], 10, 1);
    const_str_plain_write_code = UNSTREAM_STRING_ASCII(&constant_bin[ 357 ], 10, 1);
    const_str_plain_QDockWidget = UNSTREAM_STRING_ASCII(&constant_bin[ 25471 ], 11, 1);
    const_str_plain_QFormLayout = UNSTREAM_STRING_ASCII(&constant_bin[ 11520 ], 11, 1);
    const_str_plain_QGridLayout = UNSTREAM_STRING_ASCII(&constant_bin[ 13284 ], 11, 1);
    const_str_plain_QListWidget = UNSTREAM_STRING_ASCII(&constant_bin[ 13490 ], 11, 1);
    const_str_plain_QMainWindow = UNSTREAM_STRING_ASCII(&constant_bin[ 25482 ], 11, 1);
    const_str_plain_QMetaObject = UNSTREAM_STRING_ASCII(&constant_bin[ 11144 ], 11, 1);
    const_str_plain_QPushButton = UNSTREAM_STRING_ASCII(&constant_bin[ 2133 ], 11, 1);
    const_str_plain_QScrollArea = UNSTREAM_STRING_ASCII(&constant_bin[ 11023 ], 11, 1);
    const_str_plain_QSizePolicy = UNSTREAM_STRING_ASCII(&constant_bin[ 13794 ], 11, 1);
    const_str_plain_QSpacerItem = UNSTREAM_STRING_ASCII(&constant_bin[ 11499 ], 11, 1);
    const_str_plain_QTreeWidget = UNSTREAM_STRING_ASCII(&constant_bin[ 11253 ], 11, 1);
    const_str_plain___getitem__ = UNSTREAM_STRING_ASCII(&constant_bin[ 13182 ], 11, 1);
    const_str_plain___package__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25493 ], 11, 1);
    const_str_plain___prepare__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25504 ], 11, 1);
    const_str_plain_ascii_upper = UNSTREAM_STRING_ASCII(&constant_bin[ 2968 ], 11, 1);
    const_str_plain_classmethod = UNSTREAM_STRING_ASCII(&constant_bin[ 963 ], 11, 1);
    const_str_plain_getIndenter = UNSTREAM_STRING_ASCII(&constant_bin[ 324 ], 11, 1);
    const_str_plain_getProperty = UNSTREAM_STRING_ASCII(&constant_bin[ 19492 ], 11, 1);
    const_str_plain_import_from = UNSTREAM_STRING_ASCII(&constant_bin[ 4821 ], 11, 1);
    const_str_plain_indentwidth = UNSTREAM_STRING_ASCII(&constant_bin[ 429 ], 11, 1);
    const_str_plain_instantiate = UNSTREAM_STRING_ASCII(&constant_bin[ 10393 ], 11, 1);
    const_str_plain_orientation = UNSTREAM_STRING_ASCII(&constant_bin[ 18730 ], 11, 1);
    const_str_plain_rightMargin = UNSTREAM_STRING_ASCII(&constant_bin[ 25515 ], 11, 1);
    const_str_plain_setProperty = UNSTREAM_STRING_ASCII(&constant_bin[ 25526 ], 11, 1);
    const_str_plain_signal_name = UNSTREAM_STRING_ASCII(&constant_bin[ 12290 ], 11, 1);
    const_str_plain_widgetClass = UNSTREAM_STRING_ASCII(&constant_bin[ 25537 ], 11, 1);
    const_tuple_str_empty_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_empty_tuple, 0, const_str_empty); Py_INCREF(const_str_empty);
    const_str_plain_QActionGroup = UNSTREAM_STRING_ASCII(&constant_bin[ 11389 ], 12, 1);
    const_str_plain_QApplication = UNSTREAM_STRING_ASCII(&constant_bin[ 4336 ], 12, 1);
    const_str_plain_QButtonGroup = UNSTREAM_STRING_ASCII(&constant_bin[ 13638 ], 12, 1);
    const_str_plain_QTableWidget = UNSTREAM_STRING_ASCII(&constant_bin[ 12054 ], 12, 1);
    const_str_plain___builtins__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25548 ], 12, 1);
    const_str_plain___compiled__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25560 ], 12, 1);
    const_str_plain___qualname__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25572 ], 12, 1);
    const_str_plain_bottomMargin = UNSTREAM_STRING_ASCII(&constant_bin[ 25584 ], 12, 1);
    const_str_plain_from_imports = UNSTREAM_STRING_ASCII(&constant_bin[ 4778 ], 12, 1);
    const_str_plain_getAttribute = UNSTREAM_STRING_ASCII(&constant_bin[ 18872 ], 12, 1);
    const_str_plain_has_location = UNSTREAM_STRING_ASCII(&constant_bin[ 25596 ], 12, 1);
    const_str_plain_i18n_context = UNSTREAM_STRING_ASCII(&constant_bin[ 1160 ], 12, 1);
    const_str_plain_i18n_strings = UNSTREAM_STRING_ASCII(&constant_bin[ 1055 ], 12, 1);
    const_str_plain_is_attribute = UNSTREAM_STRING_ASCII(&constant_bin[ 25608 ], 12, 1);
    const_str_plain_moduleMember = UNSTREAM_STRING_ASCII(&constant_bin[ 599 ], 12, 1);
    const_str_plain_pyuicMargins = UNSTREAM_STRING_ASCII(&constant_bin[ 18386 ], 12, 1);
    const_str_plain_pyuicSpacing = UNSTREAM_STRING_ASCII(&constant_bin[ 19514 ], 12, 1);
    const_str_plain_qtgui_module = UNSTREAM_STRING_ASCII(&constant_bin[ 15759 ], 12, 1);
    const_str_plain_set_base_dir = UNSTREAM_STRING_ASCII(&constant_bin[ 15852 ], 12, 1);
    const_str_plain_staticmethod = UNSTREAM_STRING_ASCII(&constant_bin[ 1502 ], 12, 1);
    const_str_plain_topLevelItem = UNSTREAM_STRING_ASCII(&constant_bin[ 11177 ], 12, 1);
    const_str_plain__QtGuiWrapper = UNSTREAM_STRING_ASCII(&constant_bin[ 727 ], 13, 1);
    const_str_plain___metaclass__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25620 ], 13, 1);
    const_str_plain__initializing = UNSTREAM_STRING_ASCII(&constant_bin[ 25633 ], 13, 1);
    const_str_plain_createQObject = UNSTREAM_STRING_ASCII(&constant_bin[ 16236 ], 13, 1);
    const_str_plain_creatorPolicy = UNSTREAM_STRING_ASCII(&constant_bin[ 25646 ], 13, 1);
    const_str_plain_delayed_props = UNSTREAM_STRING_ASCII(&constant_bin[ 25659 ], 13, 1);
    const_str_plain_qtcore_module = UNSTREAM_STRING_ASCII(&constant_bin[ 25672 ], 13, 1);
    const_str_plain_setProperties = UNSTREAM_STRING_ASCII(&constant_bin[ 17912 ], 13, 1);
    const_tuple_str_chr_124_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_chr_124_tuple, 0, const_str_chr_124); Py_INCREF(const_str_chr_124);
    const_tuple_str_plain_s_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_s_tuple, 0, const_str_plain_s); Py_INCREF(const_str_plain_s);
    const_tuple_type_object_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_type_object_tuple, 0, (PyObject *)&PyBaseObject_Type); Py_INCREF((PyObject *)&PyBaseObject_Type);
    const_str_plain_ProxyMetaclass = UNSTREAM_STRING_ASCII(&constant_bin[ 563 ], 14, 1);
    const_str_plain_QDoubleSpinBox = UNSTREAM_STRING_ASCII(&constant_bin[ 11274 ], 14, 1);
    const_str_plain_QObjectCreator = UNSTREAM_STRING_ASCII(&constant_bin[ 3330 ], 14, 1);
    const_str_plain_QStackedWidget = UNSTREAM_STRING_ASCII(&constant_bin[ 12241 ], 14, 1);
    const_str_plain__ModuleWrapper = UNSTREAM_STRING_ASCII(&constant_bin[ 801 ], 14, 1);
    const_str_plain___orig_bases__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25685 ], 14, 1);
    const_str_plain_qobjectcreator = UNSTREAM_STRING_ASCII(&constant_bin[ 10327 ], 14, 1);
    const_str_plain_strict_getattr = UNSTREAM_STRING_ASCII(&constant_bin[ 633 ], 14, 1);
    const_str_plain_toplevelWidget = UNSTREAM_STRING_ASCII(&constant_bin[ 25699 ], 14, 1);
    const_str_plain_verticalHeader = UNSTREAM_STRING_ASCII(&constant_bin[ 13140 ], 14, 1);
    const_slice_int_pos_1_none_none = PySlice_New(const_int_pos_1, Py_None, Py_None);
    const_slice_none_int_neg_1_none = PySlice_New(Py_None, const_int_neg_1, Py_None);
    const_slice_none_int_neg_2_none = PySlice_New(Py_None, const_int_neg_2, Py_None);
    const_slice_none_int_neg_3_none = PySlice_New(Py_None, const_int_neg_3, Py_None);
    const_str_plain_DynamicUILoader = UNSTREAM_STRING_ASCII(&constant_bin[ 14656 ], 15, 1);
    const_str_plain_QAbstractButton = UNSTREAM_STRING_ASCII(&constant_bin[ 2096 ], 15, 1);
    const_str_plain_QLinearGradient = UNSTREAM_STRING_ASCII(&constant_bin[ 10869 ], 15, 1);
    const_str_plain_QListWidgetItem = UNSTREAM_STRING_ASCII(&constant_bin[ 13538 ], 15, 1);
    const_str_plain_QRadialGradient = UNSTREAM_STRING_ASCII(&constant_bin[ 11688 ], 15, 1);
    const_str_plain_QTreeWidgetItem = UNSTREAM_STRING_ASCII(&constant_bin[ 12950 ], 15, 1);
    const_str_plain___mro_entries__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25713 ], 15, 1);
    const_str_plain_addCustomWidget = UNSTREAM_STRING_ASCII(&constant_bin[ 16783 ], 15, 1);
    const_str_plain_findQObjectType = UNSTREAM_STRING_ASCII(&constant_bin[ 16614 ], 15, 1);
    const_str_plain_resource_suffix = UNSTREAM_STRING_ASCII(&constant_bin[ 4798 ], 15, 1);
    const_str_plain_setDelayedProps = UNSTREAM_STRING_ASCII(&constant_bin[ 8907 ], 15, 1);
    const_str_plain_verticalSpacing = UNSTREAM_STRING_ASCII(&constant_bin[ 25728 ], 15, 1);
    const_tuple_str_plain_obj_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_obj_tuple, 0, const_str_plain_obj); Py_INCREF(const_str_plain_obj);
    const_str_plain_NoSuchClassError = UNSTREAM_STRING_ASCII(&constant_bin[ 2822 ], 16, 1);
    const_str_plain_QConicalGradient = UNSTREAM_STRING_ASCII(&constant_bin[ 14450 ], 16, 1);
    const_str_plain_QTableWidgetItem = UNSTREAM_STRING_ASCII(&constant_bin[ 12054 ], 16, 1);
    const_str_plain___getattribute__ = UNSTREAM_STRING_ASCII(&constant_bin[ 9998 ], 16, 1);
    const_str_plain__writeOutImports = UNSTREAM_STRING_ASCII(&constant_bin[ 10036 ], 16, 1);
    const_str_plain_horizontalHeader = UNSTREAM_STRING_ASCII(&constant_bin[ 13417 ], 16, 1);
    const_str_plain_isSortingEnabled = UNSTREAM_STRING_ASCII(&constant_bin[ 25743 ], 16, 1);
    const_str_plain_no_instantiation = UNSTREAM_STRING_ASCII(&constant_bin[ 25759 ], 16, 1);
    const_str_plain_qtwidgets_module = UNSTREAM_STRING_ASCII(&constant_bin[ 25775 ], 16, 1);
    const_str_plain_widgetPluginPath = UNSTREAM_STRING_ASCII(&constant_bin[ 2374 ], 16, 1);
    const_tuple_str_plain_self_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    const_str_plain_LiteralProxyClass = UNSTREAM_STRING_ASCII(&constant_bin[ 1121 ], 17, 1);
    const_str_plain_NoSuchWidgetError = UNSTREAM_STRING_ASCII(&constant_bin[ 2567 ], 17, 1);
    const_str_plain_WidgetPluginError = UNSTREAM_STRING_ASCII(&constant_bin[ 2528 ], 17, 1);
    const_str_plain__QtWidgetsWrapper = UNSTREAM_STRING_ASCII(&constant_bin[ 762 ], 17, 1);
    const_str_plain___class_getitem__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25791 ], 17, 1);
    const_str_plain_add_dll_directory = UNSTREAM_STRING_ASCII(&constant_bin[ 25808 ], 17, 1);
    const_str_plain_horizontalSpacing = UNSTREAM_STRING_ASCII(&constant_bin[ 25825 ], 17, 1);
    const_str_plain_setSortingEnabled = UNSTREAM_STRING_ASCII(&constant_bin[ 25842 ], 17, 1);
    const_tuple_str_plain_class_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_class_tuple, 0, const_str_plain_class); Py_INCREF(const_str_plain_class);
    const_str_plain__ascii_trans_table = UNSTREAM_STRING_ASCII(&constant_bin[ 2723 ], 18, 1);
    const_str_plain_connectSlotsByName = UNSTREAM_STRING_ASCII(&constant_bin[ 11156 ], 18, 1);
    const_str_plain_createCodeIndenter = UNSTREAM_STRING_ASCII(&constant_bin[ 389 ], 18, 1);
    const_str_plain_verticalHeaderItem = UNSTREAM_STRING_ASCII(&constant_bin[ 25859 ], 18, 1);
    const_tuple_str_plain_string_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_string_tuple, 0, const_str_plain_string); Py_INCREF(const_str_plain_string);
    const_str_plain_LoaderCreatorPolicy = UNSTREAM_STRING_ASCII(&constant_bin[ 2279 ], 19, 1);
    const_str_plain__CustomWidgetLoader = UNSTREAM_STRING_ASCII(&constant_bin[ 837 ], 19, 1);
    const_str_plain_createModuleWrapper = UNSTREAM_STRING_ASCII(&constant_bin[ 10589 ], 19, 1);
    const_str_plain_NUITKA_PACKAGE_PyQt5 = UNSTREAM_STRING_ASCII(&constant_bin[ 8750 ], 20, 1);
    const_str_plain_createToplevelWidget = UNSTREAM_STRING_ASCII(&constant_bin[ 8952 ], 20, 1);
    const_str_plain_horizontalHeaderItem = UNSTREAM_STRING_ASCII(&constant_bin[ 25877 ], 20, 1);
    const_tuple_str_plain_StringIO_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_StringIO_tuple, 0, const_str_plain_StringIO); Py_INCREF(const_str_plain_StringIO);
    const_tuple_str_plain_UIParser_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_UIParser_tuple, 0, const_str_plain_UIParser); Py_INCREF(const_str_plain_UIParser);
    const_tuple_str_plain_property_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_property_tuple, 0, const_str_plain_property); Py_INCREF(const_str_plain_property);
    const_str_plain_CompilerCreatorPolicy = UNSTREAM_STRING_ASCII(&constant_bin[ 281 ], 21, 1);
    const_tuple_str_plain___class___tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain___class___tuple, 0, const_str_plain___class__); Py_INCREF(const_str_plain___class__);
    const_tuple_str_plain_as_string_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_as_string_tuple, 0, const_str_plain_as_string); Py_INCREF(const_str_plain_as_string);
    const_tuple_str_plain_Properties_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_Properties_tuple, 0, const_str_plain_Properties); Py_INCREF(const_str_plain_Properties);
    const_tuple_str_plain_write_code_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_write_code_tuple, 0, const_str_plain_write_code); Py_INCREF(const_str_plain_write_code);
    const_str_plain_NUITKA_PACKAGE_PyQt5_uic = UNSTREAM_STRING_ASCII(&constant_bin[ 8750 ], 24, 1);
    const_str_plain_UnsupportedPropertyError = UNSTREAM_STRING_ASCII(&constant_bin[ 2922 ], 24, 1);
    const_str_plain_createCustomWidgetLoader = UNSTREAM_STRING_ASCII(&constant_bin[ 10543 ], 24, 1);
    const_str_plain_createQtGuiWidgetsWrappers = UNSTREAM_STRING_ASCII(&constant_bin[ 10426 ], 26, 1);
    const_str_plain_submodule_search_locations = UNSTREAM_STRING_ASCII(&constant_bin[ 25897 ], 26, 1);
    const_tuple_str_plain_ProxyMetaclass_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_ProxyMetaclass_tuple, 0, const_str_plain_ProxyMetaclass); Py_INCREF(const_str_plain_ProxyMetaclass);
    const_dict_51eb06cf18b562904cb641f9f5ce3334 = _PyDict_NewPresized( 1 );
    PyDict_SetItem(const_dict_51eb06cf18b562904cb641f9f5ce3334, const_str_plain_is_attribute, Py_False);
    assert(PyDict_Size(const_dict_51eb06cf18b562904cb641f9f5ce3334) == 1);
    const_tuple_str_plain_self_str_plain_s_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_s_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_s_tuple, 1, const_str_plain_s); Py_INCREF(const_str_plain_s);
    const_tuple_str_plain_text_str_plain_x_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_text_str_plain_x_tuple, 0, const_str_plain_text); Py_INCREF(const_str_plain_text);
    PyTuple_SET_ITEM(const_tuple_str_plain_text_str_plain_x_tuple, 1, const_str_plain_x); Py_INCREF(const_str_plain_x);
    const_tuple_str_plain_cls_str_plain_name_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_cls_str_plain_name_tuple, 0, const_str_plain_cls); Py_INCREF(const_str_plain_cls);
    PyTuple_SET_ITEM(const_tuple_str_plain_cls_str_plain_name_tuple, 1, const_str_plain_name); Py_INCREF(const_str_plain_name);
    const_tuple_str_plain_self_str_plain_cls_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_cls_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_cls_tuple, 1, const_str_plain_cls); Py_INCREF(const_str_plain_cls);
    const_tuple_str_plain_self_str_plain_r_op_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_r_op_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_r_op_tuple, 1, const_str_plain_r_op); Py_INCREF(const_str_plain_r_op);
    const_tuple_str_plain_self_str_plain_other_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_other_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_other_tuple, 1, const_str_plain_other); Py_INCREF(const_str_plain_other);
    const_str_digest_1c75306b53bdb8e43cd18449de6927ae = UNSTREAM_STRING_ASCII(&constant_bin[ 25923 ], 9, 0);
    const_str_digest_22116dbcc880f5504e969642694bea9a = UNSTREAM_STRING_ASCII(&constant_bin[ 17412 ], 17, 0);
    const_str_digest_25731c733fd74e8333aa29126ce85686 = UNSTREAM_STRING_ASCII(&constant_bin[ 4400 ], 2, 0);
    const_str_digest_2fb35f5b371e4357763cfefa063b5165 = UNSTREAM_STRING_ASCII(&constant_bin[ 25932 ], 5, 0);
    const_str_digest_2fe71b40974e92f7a4ed2043bfd21fa9 = UNSTREAM_STRING_ASCII(&constant_bin[ 25937 ], 4, 0);
    const_str_digest_3114c7847ed30512509505e34fc4f6e0 = UNSTREAM_STRING_ASCII(&constant_bin[ 11998 ], 5, 0);
    const_str_digest_35d21bc483d4b284491535cb2e41474a = UNSTREAM_STRING_ASCII(&constant_bin[ 25941 ], 64, 0);
    const_str_digest_45e4dde2057b0bf276d6a84f4c917d27 = UNSTREAM_STRING_ASCII(&constant_bin[ 5001 ], 7, 0);
    const_str_digest_4d848f1798a02d9a0d913955a64e8e94 = UNSTREAM_STRING_ASCII(&constant_bin[ 16931 ], 17, 0);
    const_str_digest_50c57a23be6c5bc9e9afc5f4ec8bf468 = UNSTREAM_STRING_ASCII(&constant_bin[ 26005 ], 10, 0);
    const_str_digest_5bfaf90dbd407b4fc29090c8f6415242 = UNSTREAM_STRING_ASCII(&constant_bin[ 26015 ], 9, 0);
    const_str_digest_75fd71b1edada749c2ef7ac810062295 = UNSTREAM_STRING_ASCII(&constant_bin[ 26024 ], 46, 0);
    const_str_digest_7cab9bbb3c340249be5d99a622d04956 = UNSTREAM_STRING_ASCII(&constant_bin[ 26070 ], 17, 0);
    const_str_digest_7cb7e1a5659547478f12d8fe755efd75 = UNSTREAM_STRING_ASCII(&constant_bin[ 25937 ], 2, 0);
    const_str_digest_802d97a8584e66528f40ec5b87c9e84a = UNSTREAM_STRING_ASCII(&constant_bin[ 4180 ], 3, 0);
    const_str_digest_80c859bc51921fcf1a6ab24d69109fda = UNSTREAM_STRING_ASCII(&constant_bin[ 26087 ], 35, 0);
    const_str_digest_8e8dd3afae40897c981713d7a882d373 = UNSTREAM_STRING_ASCII(&constant_bin[ 26122 ], 26, 0);
    const_str_digest_9816e8d1552296af90d250823c964059 = UNSTREAM_STRING_ASCII(&constant_bin[ 26148 ], 46, 0);
    const_str_digest_a863bf128934a98648a1a5627a88779d = UNSTREAM_STRING_ASCII(&constant_bin[ 25941 ], 53, 0);
    const_str_digest_aa569b191903e6c21604f529898b6160 = UNSTREAM_STRING_ASCII(&constant_bin[ 26194 ], 28, 0);
    const_str_digest_adc474dd61fbd736d69c1bac5d9712e0 = UNSTREAM_STRING_ASCII(&constant_bin[ 26222 ], 47, 0);
    const_str_digest_c3711bf97707f5fa779b1dcac0e4a551 = UNSTREAM_STRING_ASCII(&constant_bin[ 26269 ], 21, 0);
    const_str_digest_c47129e3fed991365e20c0ca6931502e = UNSTREAM_STRING_ASCII(&constant_bin[ 26290 ], 2, 0);
    const_str_digest_cd6755d620aa6bdc1a5e95a35c0b02b9 = UNSTREAM_STRING_ASCII(&constant_bin[ 26292 ], 23, 0);
    const_str_digest_db35ab94a03c3cbeb13cbe2a1d728b77 = UNSTREAM_STRING_ASCII(&constant_bin[ 4776 ], 2, 0);
    const_str_digest_de4b0c7ad68311153ea2a31151f2e46a = UNSTREAM_STRING_ASCII(&constant_bin[ 26315 ], 63, 0);
    const_str_digest_e33d037633d5a895496c949f1e0a8014 = UNSTREAM_STRING_ASCII(&constant_bin[ 9811 ], 24, 0);
    const_str_digest_e399ba4554180f37de594a6743234f17 = UNSTREAM_STRING_ASCII(&constant_bin[ 26378 ], 7, 0);
    const_str_digest_e6450f8c3c0bf1e0c454eba7478ed0c8 = UNSTREAM_STRING_ASCII(&constant_bin[ 26385 ], 17, 0);
    const_str_digest_ebebb18731664a12452b2ba6915b22ed = UNSTREAM_STRING_ASCII(&constant_bin[ 17858 ], 2, 0);
    const_str_digest_fbe37053f75eff4f1e91e745af595cf5 = UNSTREAM_STRING_ASCII(&constant_bin[ 26402 ], 7, 0);
    const_tuple_2bf0a0f73a15cf1f5a5aa16b99dd5ec6_tuple = PyTuple_New(4);
    PyTuple_SET_ITEM(const_tuple_2bf0a0f73a15cf1f5a5aa16b99dd5ec6_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_2bf0a0f73a15cf1f5a5aa16b99dd5ec6_tuple, 1, const_str_plain_widgetClass); Py_INCREF(const_str_plain_widgetClass);
    PyTuple_SET_ITEM(const_tuple_2bf0a0f73a15cf1f5a5aa16b99dd5ec6_tuple, 2, const_str_plain_baseClass); Py_INCREF(const_str_plain_baseClass);
    PyTuple_SET_ITEM(const_tuple_2bf0a0f73a15cf1f5a5aa16b99dd5ec6_tuple, 3, const_str_plain_module); Py_INCREF(const_str_plain_module);
    const_tuple_3f2f177cbcd58a6e2810b9361003d74a_tuple = PyTuple_New(4);
    PyTuple_SET_ITEM(const_tuple_3f2f177cbcd58a6e2810b9361003d74a_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_3f2f177cbcd58a6e2810b9361003d74a_tuple, 1, const_str_plain_rname); Py_INCREF(const_str_plain_rname);
    PyTuple_SET_ITEM(const_tuple_3f2f177cbcd58a6e2810b9361003d74a_tuple, 2, const_str_plain_method); Py_INCREF(const_str_plain_method);
    PyTuple_SET_ITEM(const_tuple_3f2f177cbcd58a6e2810b9361003d74a_tuple, 3, const_str_plain_args); Py_INCREF(const_str_plain_args);
    const_tuple_8b1fd1016da3eaee3145814dfe4be59a_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_8b1fd1016da3eaee3145814dfe4be59a_tuple, 0, const_str_plain_NUITKA_PACKAGE_PyQt5); Py_INCREF(const_str_plain_NUITKA_PACKAGE_PyQt5);
    PyTuple_SET_ITEM(const_tuple_8b1fd1016da3eaee3145814dfe4be59a_tuple, 1, const_str_digest_5bfaf90dbd407b4fc29090c8f6415242); Py_INCREF(const_str_digest_5bfaf90dbd407b4fc29090c8f6415242);
    const_tuple_ea9a58e3c182e55994a2e18312eb11df_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_ea9a58e3c182e55994a2e18312eb11df_tuple, 0, const_str_plain_NUITKA_PACKAGE_PyQt5_uic); Py_INCREF(const_str_plain_NUITKA_PACKAGE_PyQt5_uic);
    PyTuple_SET_ITEM(const_tuple_ea9a58e3c182e55994a2e18312eb11df_tuple, 1, const_str_digest_5bfaf90dbd407b4fc29090c8f6415242); Py_INCREF(const_str_digest_5bfaf90dbd407b4fc29090c8f6415242);
    const_tuple_str_plain_self_str_plain_context_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_context_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_context_tuple, 1, const_str_plain_context); Py_INCREF(const_str_plain_context);
    const_tuple_str_plain_self_str_plain_package_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_package_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_package_tuple, 1, const_str_plain_package); Py_INCREF(const_str_plain_package);
    const_tuple_str_plain_self_str_plain_base_dir_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_base_dir_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_base_dir_tuple, 1, const_str_plain_base_dir); Py_INCREF(const_str_plain_base_dir);
    const_tuple_str_plain_Literal_str_plain_moduleMember_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_Literal_str_plain_moduleMember_tuple, 0, const_str_plain_Literal); Py_INCREF(const_str_plain_Literal);
    PyTuple_SET_ITEM(const_tuple_str_plain_Literal_str_plain_moduleMember_tuple, 1, const_str_plain_moduleMember); Py_INCREF(const_str_plain_moduleMember);
    const_tuple_str_digest_50c57a23be6c5bc9e9afc5f4ec8bf468_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_50c57a23be6c5bc9e9afc5f4ec8bf468_tuple, 0, const_str_digest_50c57a23be6c5bc9e9afc5f4ec8bf468); Py_INCREF(const_str_digest_50c57a23be6c5bc9e9afc5f4ec8bf468);
    const_tuple_str_digest_ebebb18731664a12452b2ba6915b22ed_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_ebebb18731664a12452b2ba6915b22ed_tuple, 0, const_str_digest_ebebb18731664a12452b2ba6915b22ed); Py_INCREF(const_str_digest_ebebb18731664a12452b2ba6915b22ed);
    const_tuple_anon_function_anon_builtin_function_or_method_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_anon_function_anon_builtin_function_or_method_tuple, 0, (PyObject *)&PyFunction_Type); Py_INCREF((PyObject *)&PyFunction_Type);
    PyTuple_SET_ITEM(const_tuple_anon_function_anon_builtin_function_or_method_tuple, 1, (PyObject *)&PyCFunction_Type); Py_INCREF((PyObject *)&PyCFunction_Type);
    const_tuple_str_plain_self_str_plain_object_str_plain_slotname_tuple = PyTuple_New(3);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_object_str_plain_slotname_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_object_str_plain_slotname_tuple, 1, const_str_plain_object); Py_INCREF(const_str_plain_object);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_object_str_plain_slotname_tuple, 2, const_str_plain_slotname); Py_INCREF(const_str_plain_slotname);
    const_tuple_str_chr_92_str_digest_7cb7e1a5659547478f12d8fe755efd75_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_chr_92_str_digest_7cb7e1a5659547478f12d8fe755efd75_tuple, 0, const_str_chr_92); Py_INCREF(const_str_chr_92);
    PyTuple_SET_ITEM(const_tuple_str_chr_92_str_digest_7cb7e1a5659547478f12d8fe755efd75_tuple, 1, const_str_digest_7cb7e1a5659547478f12d8fe755efd75); Py_INCREF(const_str_digest_7cb7e1a5659547478f12d8fe755efd75);
    const_tuple_str_plain_self_str_plain_classname_str_plain_widgetname_tuple = PyTuple_New(3);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_classname_str_plain_widgetname_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_classname_str_plain_widgetname_tuple, 1, const_str_plain_classname); Py_INCREF(const_str_plain_classname);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_classname_str_plain_widgetname_tuple, 2, const_str_plain_widgetname); Py_INCREF(const_str_plain_widgetname);

#if _NUITKA_EXE
    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"executable",
        const_str_digest_35d21bc483d4b284491535cb2e41474a
    );

#ifndef _NUITKA_STANDALONE
    /* Set the "sys.prefix" path to the original one. */
    PySys_SetObject(
        (char *)"prefix",
        const_str_digest_a863bf128934a98648a1a5627a88779d
    );

    /* Set the "sys.prefix" path to the original one. */
    PySys_SetObject(
        (char *)"exec_prefix",
        const_str_digest_a863bf128934a98648a1a5627a88779d
    );


#if PYTHON_VERSION >= 300
    /* Set the "sys.base_prefix" path to the original one. */
    PySys_SetObject(
        (char *)"base_prefix",
        const_str_digest_a863bf128934a98648a1a5627a88779d
    );

    /* Set the "sys.exec_base_prefix" path to the original one. */
    PySys_SetObject(
        (char *)"base_exec_prefix",
        const_str_digest_a863bf128934a98648a1a5627a88779d
    );

#endif
#endif
#endif

    static PyTypeObject Nuitka_VersionInfoType;

    // Same fields as "sys.version_info" except no serial number.
    static PyStructSequence_Field Nuitka_VersionInfoFields[] = {
        {(char *)"major", (char *)"Major release number"},
        {(char *)"minor", (char *)"Minor release number"},
        {(char *)"micro", (char *)"Micro release number"},
        {(char *)"releaselevel", (char *)"'alpha', 'beta', 'candidate', or 'release'"},
        {0}
    };

    static PyStructSequence_Desc Nuitka_VersionInfoDesc = {
        (char *)"__nuitka_version__",                                    /* name */
        (char *)"__compiled__\n\nVersion information as a named tuple.", /* doc */
        Nuitka_VersionInfoFields,                                        /* fields */
        4
    };

    PyStructSequence_InitType(&Nuitka_VersionInfoType, &Nuitka_VersionInfoDesc);

    Nuitka_dunder_compiled_value = PyStructSequence_New(&Nuitka_VersionInfoType);
    assert(Nuitka_dunder_compiled_value != NULL);

    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 0, PyInt_FromLong(0));
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 1, PyInt_FromLong(6));
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 2, PyInt_FromLong(7));

#if PYTHON_VERSION < 300
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 3, PyString_FromString("release"));
#else
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 3, PyUnicode_FromString("release"));
#endif
    // Prevent users from creating the Nuitka version type object.
    Nuitka_VersionInfoType.tp_init = NULL;
    Nuitka_VersionInfoType.tp_new = NULL;


}

// In debug mode we can check that the constants were not tampered with in any
// given moment. We typically do it at program exit, but we can add extra calls
// for sanity.
#ifndef __NUITKA_NO_ASSERT__
void checkGlobalConstants(void) {

}
#endif

void createGlobalConstants(void) {
    if (_sentinel_value == NULL) {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr(NULL, NULL);
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New((void *)27, "sentinel", NULL);
#endif
        assert(_sentinel_value);

        _createGlobalConstants();
    }
}
